# Chapter 10: Data Handling with Pandas

**B.Pharm companion Jupyter notebook — worked examples and concept demonstrations**

## Chapter focus

Create pandas Series and DataFrames, import CSV and Excel data, inspect structure and identify issues before analysis.

## Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

## Important notes and how to use this notebook

1. Use a Python 3 kernel. Read the problem and algorithm, predict the result, then run the cell with **Shift+Enter**.
2. Choose **Restart Kernel and Run All Cells** to reproduce the saved outputs. Run from top to bottom; later demonstrations may use earlier variables.
3. Outputs below code cells were produced by execution. Paths, versions, memory diagnostics and set display order can differ between computers.
4. All records are simulated for education. Retain units and distinguish a descriptive result from a clinical or regulatory decision.
5. Files written by examples are kept in `outputs/chapter_10`. Rerunning a file-writing example replaces its own generated output.

**Packages:** `numpy`, `pandas`, `openpyxl`. If required, run this once in a separate cell and restart the kernel:

```python
%pip install numpy pandas openpyxl
```

**Data files:** `adr_reports.xlsx`, `dose_series.csv`, `pk_study.csv`.

Extract the Chapter 10 dataset ZIP beside this notebook, preserving `data/chapter_10`. Individual data files can also be placed in the same folder as the notebook. The setup cell searches both locations.


In [1]:
from pathlib import Path

WORKSHOP_ROOT = Path.cwd().resolve()
OUTPUT_DIR = WORKSHOP_ROOT / "outputs" / "chapter_10"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

required_files = ['adr_reports.xlsx', 'dose_series.csv', 'pk_study.csv']
candidates = [WORKSHOP_ROOT / "data" / "chapter_10", WORKSHOP_ROOT]
DATA_DIR = next((folder for folder in candidates
                 if all((folder / name).is_file() for name in required_files)), None)
if DATA_DIR is None:
    raise FileNotFoundError(
        "Extract the chapter dataset ZIP beside this notebook or put all listed data files in the notebook folder."
    )
print("Companion data files found:", len(required_files))

print("Chapter 10 ready. Generated files: outputs/chapter_10")

Companion data files found: 3
Chapter 10 ready. Generated files: outputs/chapter_10


## Contents

- [01. 10.5.2 Install from a Jupyter Cell](#example-10-1)
- [02. 10.5.3 Import and Version Check](#example-10-2)
- [03. 10.6.1 Creating a Series from a Python List](#example-10-3)
- [04. 10.6.2 Creating a Series with Custom Index Labels and a Name](#example-10-4)
- [05. 10.6.3 Creating a Series from a NumPy Array](#example-10-5)
- [06. 10.6.4 Creating a Series from a Dictionary](#example-10-6)
- [07. 10.6.5 Important Series Attributes and Basic Access](#example-10-7)
- [08. Worked Program 1: Create and Interpret a Labelled Dose Series](#example-10-8)
- [09. 10.7.1 Creating a DataFrame from a Dictionary of Lists](#example-10-9)
- [10. 10.7.2 Creating a DataFrame from a List of Dictionaries](#example-10-10)
- [11. 10.7.3 Creating a DataFrame from Series Objects](#example-10-11)
- [12. 10.7.4 Creating a DataFrame from a NumPy Array](#example-10-12)
- [13. 10.7.5 Important DataFrame Attributes](#example-10-13)
- [14. Worked Program 2: Create a Batch DataFrame from a Dictionary](#example-10-14)
- [15. Worked Program 3: Create a Small PK DataFrame from a List of Records](#example-10-15)
- [16. 10.10 Project Folders and File Paths in Jupyter Notebook](#example-10-16)
- [17. 10.11 Importing CSV Files with pd.read_csv()](#example-10-17)
- [18. Worked Program 4: Import a PK Study CSV File](#example-10-18)
- [19. 10.12 Importing Excel Files with pd.read_excel()](#example-10-19)
- [20. Worked Program 5: Import an ADR Excel Workbook](#example-10-20)
- [21. 10.15.1 head() - Preview the First Rows](#example-10-21)
- [22. 10.15.2 tail() - Preview the Last Rows](#example-10-22)
- [23. 10.15.3 shape - Count Rows and Columns](#example-10-23)
- [24. 10.15.4 columns - Read the Column Names](#example-10-24)
- [25. 10.15.5 dtypes - Check How Columns Were Read](#example-10-25)
- [26. 10.15.6 info() - Structural Summary and Non-Null Counts](#example-10-26)
- [27. 10.15.7 describe() - Numeric Descriptive Summary](#example-10-27)
- [28. 10.15.8 describe(include='object') - Text and Category Summary](#example-10-28)
- [29. Worked Program 6: Perform a First Inspection of the PK Dataset](#example-10-29)
- [30. Worked Program 7: Inspect the ADR Workbook and Identify Structural Issues](#example-10-30)
- [31. Worked Program 8: Chapter 10 Integrated File-Inspection Workflow](#example-10-31)

<a id="example-10-1"></a>

## 01. 10.5.2 Install from a Jupyter Cell

### Problem statement

Demonstrate install from a Jupyter Cell using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support install from a jupyter cell and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `importlib.metadata`.
2. Display the results for inspection.

### Important notes

Installation is optional preparation, so it is shown in the opening notes. This executable cell verifies installed versions without changing the environment.

### Code and executed output

The output appears directly below the code cell.

In [2]:
from importlib.metadata import version
print("numpy:", version("numpy"))
print("pandas:", version("pandas"))
print("openpyxl:", version("openpyxl"))

numpy: 2.3.5
pandas: 2.2.3
openpyxl: 3.1.5


### Explanation

The exact version numbers depend on the student computer. %pip is a Jupyter magic command. If installation completes but import still fails, restart the kernel and run the import cell again.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-2"></a>

## 02. 10.5.3 Import and Version Check

### Problem statement

Demonstrate import and Version Check using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support import and version check and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [3]:
import pandas as pd
print("Pandas version:", pd.__version__)

Pandas version: 2.2.3


### Explanation

pd is the conventional alias used in most Pandas examples. __version__ helps record the software environment used to execute a notebook. This is useful when notebooks are shared across different computers.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-3"></a>

## 03. 10.6.1 Creating a Series from a Python List

### Problem statement

Demonstrate creating a Series from a Python List using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support creating a series from a python list and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.Series([500, 650, 400])` in `dose_mg`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [4]:
import pandas as pd

dose_mg = pd.Series([500, 650, 400])
print(dose_mg)

0    500
1    650
2    400
dtype: int64


### Explanation

data contains the values. Because index is not supplied, Pandas creates 0, 1, and 2. The values are integers, so an integer dtype is used. The exact integer type can vary by platform.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-4"></a>

## 04. 10.6.2 Creating a Series with Custom Index Labels and a Name

### Problem statement

Demonstrate creating a Series with Custom Index Labels and a Name using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support creating a series with custom index labels and a name and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.Series([500, 650, 400, 500], index=['P01', 'P02', 'P03', 'P04'], name='dose_mg')` in `dose_mg`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [5]:
import pandas as pd

dose_mg = pd.Series(
    [500, 650, 400, 500],
    index=["P01", "P02", "P03", "P04"],
    name="dose_mg"
)
print(dose_mg)

P01    500
P02    650
P03    400
P04    500
Name: dose_mg, dtype: int64


### Explanation

The data parameter supplies four dose values. index supplies four matching labels, so the lengths must agree. name labels the Series as dose_mg. The units are made visible in the name, which reduces ambiguity in later code.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-5"></a>

## 05. 10.6.3 Creating a Series from a NumPy Array

### Problem statement

Demonstrate creating a Series from a NumPy Array using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support creating a series from a numpy array and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `numpy`.
2. Import `pandas`.
3. Store `np.array([12.4, 88.6, 145.2, 96.1])` in `conc`.
4. Store `pd.Series(conc, index=[0.5, 1.0, 2.0, 4.0], name='conc_ng_ml')` in `conc_series`.
5. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [6]:
import numpy as np
import pandas as pd

conc = np.array([12.4, 88.6, 145.2, 96.1])
conc_series = pd.Series(conc, index=[0.5, 1.0, 2.0, 4.0],
                        name="conc_ng_ml")
print(conc_series)

0.5     12.4
1.0     88.6
2.0    145.2
4.0     96.1
Name: conc_ng_ml, dtype: float64


### Explanation

The NumPy array supplies the concentration values. The custom index stores the sampling times in hours. The Series name includes the concentration unit. This makes the Series suitable for simple labelled PK demonstrations.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-6"></a>

## 06. 10.6.4 Creating a Series from a Dictionary

### Problem statement

Demonstrate creating a Series from a Dictionary using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support creating a series from a dictionary and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.Series({'B001': 99.6, 'B002': 100.4, 'B003': 98.9}, name='assay_percent')` in `assay`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [7]:
import pandas as pd

assay = pd.Series({
    "B001": 99.6,
    "B002": 100.4,
    "B003": 98.9
}, name="assay_percent")
print(assay)

B001     99.6
B002    100.4
B003     98.9
Name: assay_percent, dtype: float64


### Explanation

The batch identifiers are used as the Series index. The numerical dictionary values become assay percentages. This is convenient when each value already has a natural label.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-7"></a>

## 07. 10.6.5 Important Series Attributes and Basic Access

### Problem statement

Demonstrate important Series Attributes and Basic Access using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support important series attributes and basic access and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.Series([500, 650, 400, 500], index=['P01', 'P02', 'P03', 'P04'], name='dose_mg')` in `dose_mg`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [8]:
import pandas as pd

dose_mg = pd.Series(
    [500, 650, 400, 500],
    index=["P01", "P02", "P03", "P04"],
    name="dose_mg"
)

print(dose_mg.index)
print(dose_mg.values)
print(dose_mg.shape)
print(dose_mg.size)
print(dose_mg.loc["P02"])
print(dose_mg.iloc[0])

Index(['P01', 'P02', 'P03', 'P04'], dtype='object')
[500 650 400 500]
(4,)
4
650
500


### Explanation

The Series contains four values. loc uses the label P02 and returns 650, while iloc uses position 0 and returns the first value, 500. The two forms answer different questions: which labelled observation versus which physical position.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-8"></a>

## 08. Worked Program 1: Create and Interpret a Labelled Dose Series

### Problem statement

Create a Pandas Series containing four simulated dose values indexed by subject ID. Display the Series, calculate the mean and maximum, and retrieve the value for subject P02.

### Objective

To practise creation and basic interpretation of a labelled one-dimensional pharmaceutical variable in Pandas.

### Pharmacy context

data contains four classroom values. index connects each value to a subject label. name="dose_mg" records the unit in the Series name. mean() returns 512.5 mg for these four simulated observations, max() returns 650 mg, and loc["P02"] shows that the 650 mg observation belongs to P02. These outputs describe the dataset only; they are not dose recommendations.

### Algorithm

1. Import Pandas as pd.
2. Create a Series containing four dose values.
3. Use subject identifiers as the index.
4. Assign the name dose_mg to preserve the unit in the variable label.
5. Calculate the mean and maximum dose values.
6. Retrieve the dose for P02 using label-based access.
7. Display the results with units.

### Variables and parameters

| Variable / Parameter | Meaning | Example / Unit |
| --- | --- | --- |
| dose_mg | Series of simulated doses | mg |
| index | Subject labels | P01-P04 |
| name | Name of the Series | dose_mg |
| mean() | Arithmetic mean of the Series | mg |
| max() | Largest value in the Series | mg |
| loc["P02"] | Label-based lookup | P02 |

### Code and executed output

The output appears directly below the code cell.

In [9]:
import pandas as pd

dose_mg = pd.Series(
    [500, 650, 400, 500],
    index=["P01", "P02", "P03", "P04"],
    name="dose_mg"
)

print(dose_mg)
print("Mean dose:", round(dose_mg.mean(), 1), "mg")
print("Maximum dose:", dose_mg.max(), "mg")
print("Subject P02 dose:", dose_mg.loc["P02"], "mg")

P01    500
P02    650
P03    400
P04    500
Name: dose_mg, dtype: int64
Mean dose: 512.5 mg
Maximum dose: 650 mg
Subject P02 dose: 650 mg


### Explanation

pd.Series() constructs the labelled variable. mean() and max() operate on the numeric values, while loc[] retrieves a value by its label. The program does not require a loop because the Series already represents the collection as one object.

### Interpretation

data contains four classroom values. index connects each value to a subject label. name="dose_mg" records the unit in the Series name. mean() returns 512.5 mg for these four simulated observations, max() returns 650 mg, and loc["P02"] shows that the 650 mg observation belongs to P02. These outputs describe the dataset only; they are not dose recommendations.

<a id="example-10-9"></a>

## 09. 10.7.1 Creating a DataFrame from a Dictionary of Lists

### Problem statement

Demonstrate creating a DataFrame from a Dictionary of Lists using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support creating a dataframe from a dictionary of lists and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Create or calculate `data` from the values shown in the code.
3. Store `pd.DataFrame(data)` in `df`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [10]:
import pandas as pd

data = {
    "batch_id": ["B001", "B002", "B003"],
    "label_claim_mg": [500, 500, 250],
    "assay_percent": [99.6, 100.4, 98.9]
}

df = pd.DataFrame(data)
print(df)

  batch_id  label_claim_mg  assay_percent
0     B001             500           99.6
1     B002             500          100.4
2     B003             250           98.9


### Explanation

The dictionary keys become column names. Each list supplies one column. The lists must have compatible lengths. The default row index is 0, 1, and 2.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-10"></a>

## 10. 10.7.2 Creating a DataFrame from a List of Dictionaries

### Problem statement

Demonstrate creating a DataFrame from a List of Dictionaries using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support creating a dataframe from a list of dictionaries and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `[{'time_h': 0.0, 'conc_ng_ml': 0.0}, {'time_h': 0.5, 'conc_ng_ml': 12.4}, {'time_h': 1.0, 'conc_ng_ml': 88.6}]` in `records`.
3. Store `pd.DataFrame(records)` in `pk_small`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [11]:
import pandas as pd

records = [
    {"time_h": 0.0, "conc_ng_ml": 0.0},
    {"time_h": 0.5, "conc_ng_ml": 12.4},
    {"time_h": 1.0, "conc_ng_ml": 88.6}
]

pk_small = pd.DataFrame(records)
print(pk_small)

   time_h  conc_ng_ml
0     0.0         0.0
1     0.5        12.4
2     1.0        88.6


### Explanation

Each dictionary becomes one row, and the dictionary keys define the columns. This pattern connects directly with list-of-dictionaries work from earlier Python chapters.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-11"></a>

## 11. 10.7.3 Creating a DataFrame from Series Objects

### Problem statement

Demonstrate creating a DataFrame from Series Objects using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support creating a dataframe from series objects and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.Series(['B001', 'B002', 'B003'])` in `batch`.
3. Store `pd.Series([99.6, 100.4, 98.9])` in `assay`.
4. Store `pd.DataFrame({'batch_id': batch, 'assay_percent': assay})` in `df`.
5. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [12]:
import pandas as pd

batch = pd.Series(["B001", "B002", "B003"])
assay = pd.Series([99.6, 100.4, 98.9])

df = pd.DataFrame({
    "batch_id": batch,
    "assay_percent": assay
})
print(df)

  batch_id  assay_percent
0     B001           99.6
1     B002          100.4
2     B003           98.9


### Explanation

The two Series share the same default index, so their values align row by row. A DataFrame can therefore be viewed as a collection of aligned Series objects.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-12"></a>

## 12. 10.7.4 Creating a DataFrame from a NumPy Array

### Problem statement

Demonstrate creating a DataFrame from a NumPy Array using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support creating a dataframe from a numpy array and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `numpy`.
2. Import `pandas`.
3. Store `np.array([[0.0, 0.0], [0.5, 12.4], [1.0, 88.6]])` in `arr`.
4. Store `pd.DataFrame(arr, columns=['time_h', 'conc_ng_ml'])` in `df`.
5. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [13]:
import numpy as np
import pandas as pd

arr = np.array([[0.0, 0.0],
                [0.5, 12.4],
                [1.0, 88.6]])

df = pd.DataFrame(
    arr,
    columns=["time_h", "conc_ng_ml"]
)
print(df)

   time_h  conc_ng_ml
0     0.0         0.0
1     0.5        12.4
2     1.0        88.6


### Explanation

columns supplies the labels that the original NumPy array does not carry. This is useful when a numerical matrix needs to become a readable table.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-13"></a>

## 13. 10.7.5 Important DataFrame Attributes

### Problem statement

Demonstrate important DataFrame Attributes using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support important dataframe attributes and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Create or calculate `batch_df` from the values shown in the code.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [14]:
import pandas as pd

batch_df = pd.DataFrame({
    "batch_id": ["B001", "B002", "B003", "B004"],
    "dosage_form": ["Tablet", "Tablet", "Capsule", "Tablet"],
    "label_claim_mg": [500, 500, 250, 500],
    "assay_percent": [99.6, 100.4, 98.9, 101.1]
})

print("shape:", batch_df.shape)
print("columns:", list(batch_df.columns))
print("size:", batch_df.size)
print("rows:", len(batch_df))
print(batch_df.dtypes)

shape: (4, 4)
columns: ['batch_id', 'dosage_form', 'label_claim_mg', 'assay_percent']
size: 16
rows: 4
batch_id           object
dosage_form        object
label_claim_mg      int64
assay_percent     float64
dtype: object


### Explanation

shape shows four rows and four columns. size counts all 16 cells. len() counts rows. dtypes reveals that identifiers and dosage forms are text-like object columns, label claim is integer, and assay percentage is floating point.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-14"></a>

## 14. Worked Program 2: Create a Batch DataFrame from a Dictionary

### Problem statement

Create a DataFrame containing batch ID, dosage form, label claim, and assay percentage for four simulated batches. Display the table, shape, column names, and dtypes.

### Objective

To practise DataFrame construction from a dictionary and interpret the structure of a mixed pharmaceutical table.

### Pharmacy context

The label_claim_mg column is numeric and unit-aware; assay_percent contains decimals; batch_id and dosage_form are text categories. shape=(4,4) confirms four simulated batch records and four variables. Structural interpretation comes before any specification judgement, which is intentionally deferred.

### Algorithm

1. Import Pandas.
2. Create a dictionary containing four equal-length lists.
3. Convert the dictionary to a DataFrame.
4. Display the DataFrame.
5. Display shape and column names.
6. Display the dtype of each column.

### Variables and parameters

| Variable / Parameter | Meaning | Example / Unit |
| --- | --- | --- |
| batch_df | Batch DataFrame | 4 rows x 4 columns |
| batch_id | Synthetic batch identifier | text |
| dosage_form | Dosage form label | text |
| label_claim_mg | Label claim | mg |
| assay_percent | Simulated assay result | % |
| shape | Number of rows and columns | (4, 4) |
| dtypes | Storage type of each column | object / int64 / float64 |

### Code and executed output

The output appears directly below the code cell.

In [15]:
import pandas as pd

batch_df = pd.DataFrame({
    "batch_id": ["B001", "B002", "B003", "B004"],
    "dosage_form": ["Tablet", "Tablet", "Capsule", "Tablet"],
    "label_claim_mg": [500, 500, 250, 500],
    "assay_percent": [99.6, 100.4, 98.9, 101.1]
})

print(batch_df)
print("Shape:", batch_df.shape)
print("Columns:", list(batch_df.columns))
print(batch_df.dtypes)

  batch_id dosage_form  label_claim_mg  assay_percent
0     B001      Tablet             500           99.6
1     B002      Tablet             500          100.4
2     B003     Capsule             250           98.9
3     B004      Tablet             500          101.1
Shape: (4, 4)
Columns: ['batch_id', 'dosage_form', 'label_claim_mg', 'assay_percent']
batch_id           object
dosage_form        object
label_claim_mg      int64
assay_percent     float64
dtype: object


### Explanation

pd.DataFrame() creates the table. Each dictionary key becomes a column. shape, columns, and dtypes describe the structure without modifying it. This is the basic pattern used after importing real tabular data.

### Interpretation

The label_claim_mg column is numeric and unit-aware; assay_percent contains decimals; batch_id and dosage_form are text categories. shape=(4,4) confirms four simulated batch records and four variables. Structural interpretation comes before any specification judgement, which is intentionally deferred.

<a id="example-10-15"></a>

## 15. Worked Program 3: Create a Small PK DataFrame from a List of Records

### Problem statement

Create a five-row PK DataFrame with time and plasma concentration values, then display its shape and column names.

### Objective

To connect the list-of-dictionaries structure from earlier Python chapters with a labelled Pandas DataFrame used for PK data.

### Pharmacy context

time_h is expressed in hours and conc_ng_ml in ng/mL. The five rows describe five observations, not five different patients. The column names retain the units so that later plots or calculations are less likely to mix incompatible quantities.

### Algorithm

1. Import Pandas.
2. Create a list in which each dictionary represents one time-concentration observation.
3. Convert the list to a DataFrame.
4. Display the DataFrame.
5. Inspect the shape and column names.

### Variables and parameters

| Variable / Parameter | Meaning | Example / Unit |
| --- | --- | --- |
| records | List of row dictionaries | 5 observations |
| time_h | Time after dose | hours |
| conc_ng_ml | Plasma concentration | ng/mL |
| pk_small | Resulting DataFrame | 5 x 2 |
| shape | Rows and columns | (5, 2) |
| columns | Variable names | time_h, conc_ng_ml |

### Code and executed output

The output appears directly below the code cell.

In [16]:
import pandas as pd

records = [
    {"time_h": 0.0, "conc_ng_ml": 0.0},
    {"time_h": 0.5, "conc_ng_ml": 12.4},
    {"time_h": 1.0, "conc_ng_ml": 88.6},
    {"time_h": 2.0, "conc_ng_ml": 145.2},
    {"time_h": 4.0, "conc_ng_ml": 96.1}
]

pk_small = pd.DataFrame(records)
print(pk_small)
print("Shape:", pk_small.shape)
print("Columns:", list(pk_small.columns))

   time_h  conc_ng_ml
0     0.0         0.0
1     0.5        12.4
2     1.0        88.6
3     2.0       145.2
4     4.0        96.1
Shape: (5, 2)
Columns: ['time_h', 'conc_ng_ml']


### Explanation

Each dictionary becomes one row and the repeated dictionary keys become the column names. The result is a 5-row, 2-column DataFrame that is easier to inspect and extend than separate lists.

### Interpretation

time_h is expressed in hours and conc_ng_ml in ng/mL. The five rows describe five observations, not five different patients. The column names retain the units so that later plots or calculations are less likely to mix incompatible quantities.

<a id="example-10-16"></a>

## 16. 10.10 Project Folders and File Paths in Jupyter Notebook

### Problem statement

Demonstrate project Folders and File Paths in Jupyter Notebook using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support project folders and file paths in jupyter notebook and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pathlib`.
2. Store `Path.cwd()` in `project_folder`.
3. Store `DATA_DIR / 'pk_study.csv'` in `pk_path`.
4. Store `DATA_DIR / 'adr_reports.xlsx'` in `adr_path`.
5. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [17]:
from pathlib import Path

project_folder = Path.cwd()
pk_path = (DATA_DIR / "pk_study.csv")
adr_path = (DATA_DIR / "adr_reports.xlsx")

print("Working folder:", project_folder)
print("PK file found:", pk_path.exists())
print("ADR file found:", adr_path.exists())

Working folder: /workspace/scratch/1ff152582af4/notebook_work/execution/chapter_10
PK file found: True
ADR file found: True


### Explanation

Path.cwd() shows where relative filenames are resolved. exists() is a simple pre-check that returns True when the expected file is present. The exact working-folder path differs on each computer.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-17"></a>

## 17. 10.11 Importing CSV Files with pd.read_csv()

### Problem statement

Demonstrate importing CSV Files with pd.read_csv() using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support importing csv files with pd.read_csv() and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pathlib`.
2. Import `pandas`.
3. Store `DATA_DIR / 'pk_study.csv'` in `pk_path`.
4. Test `not pk_path.exists()` and run the matching branch.
5. Store `pd.read_csv(pk_path)` in `pk`.
6. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [18]:
from pathlib import Path
import pandas as pd

pk_path = (DATA_DIR / "pk_study.csv")
if not pk_path.exists():
    raise FileNotFoundError(
        "Place pk_study.csv in the same folder as this notebook."
    )

pk = pd.read_csv(pk_path)
print(pk.head(3))
print("Shape:", pk.shape)

  subject_id  dose_mg  time_h  conc_ng_ml  age_years  weight_kg
0        S01      500     0.5        12.4         34       68.2
1        S01      500     1.0        88.6         34       68.2
2        S01      500     2.0       145.2         34       68.2
Shape: (60, 6)


### Explanation

filepath_or_buffer receives the filename. The default comma separator and header inference are appropriate for this file, so only the filename is required. head(3) previews three rows, while shape confirms that the file produced a 60-row, 6-column DataFrame.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-18"></a>

## 18. Worked Program 4: Import a PK Study CSV File

### Problem statement

Read pk_study.csv into a DataFrame and display the first three rows, the shape, and the column names.

### Objective

To practise pd.read_csv() and verify that a PK dataset has been imported with the expected dimensions and headers.

### Pharmacy context

The expected shape is 60 x 6 because 12 synthetic subjects each have five sampling rows. The variables include subject_id, dose_mg, time_h, conc_ng_ml, age_years, and weight_kg. The units embedded in the headers reduce ambiguity. If the shape or headers differ, stop and investigate before any PK calculation.

### Algorithm

1. Import Pandas.
2. Read pk_study.csv with pd.read_csv().
3. Store the returned DataFrame in pk.
4. Display the first three rows with head(3).
5. Display pk.shape.
6. Display the column names as a Python list.

### Variables and parameters

| Variable / Parameter | Meaning | Example / Unit |
| --- | --- | --- |
| pk | Imported PK DataFrame | 60 x 6 |
| filepath_or_buffer | CSV file passed to read_csv | pk_study.csv |
| head(3) | Number of rows to preview | 3 |
| shape | Rows and columns | (60, 6) |
| columns | Imported headers | 6 names |

### Code and executed output

The output appears directly below the code cell.

In [19]:
from pathlib import Path
import pandas as pd

pk_path = (DATA_DIR / "pk_study.csv")
if not pk_path.exists():
    raise FileNotFoundError(
        "Place pk_study.csv in the same folder as this notebook."
    )

pk = pd.read_csv(pk_path)

print(pk.head(3))
print("Shape:", pk.shape)
print("Columns:", list(pk.columns))

  subject_id  dose_mg  time_h  conc_ng_ml  age_years  weight_kg
0        S01      500     0.5        12.4         34       68.2
1        S01      500     1.0        88.6         34       68.2
2        S01      500     2.0       145.2         34       68.2
Shape: (60, 6)
Columns: ['subject_id', 'dose_mg', 'time_h', 'conc_ng_ml', 'age_years', 'weight_kg']


### Explanation

pd.read_csv() returns a DataFrame. head(3) shows three records without printing all 60 rows. shape and columns are structural checks that help detect a wrong file, missing header, or unexpected delimiter before further work.

### Interpretation

The expected shape is 60 x 6 because 12 synthetic subjects each have five sampling rows. The variables include subject_id, dose_mg, time_h, conc_ng_ml, age_years, and weight_kg. The units embedded in the headers reduce ambiguity. If the shape or headers differ, stop and investigate before any PK calculation.

<a id="example-10-19"></a>

## 19. 10.12 Importing Excel Files with pd.read_excel()

### Problem statement

Demonstrate importing Excel Files with pd.read_excel() using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support importing excel files with pd.read_excel() and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pathlib`.
2. Import `pandas`.
3. Store `DATA_DIR / 'adr_reports.xlsx'` in `adr_path`.
4. Test `not adr_path.exists()` and run the matching branch.
5. Store `pd.read_excel(adr_path, sheet_name='reports', engine='openpyxl')` in `adr`.
6. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [20]:
from pathlib import Path
import pandas as pd

adr_path = (DATA_DIR / "adr_reports.xlsx")
if not adr_path.exists():
    raise FileNotFoundError(
        "Place adr_reports.xlsx in the same folder as this notebook."
    )

adr = pd.read_excel(
    adr_path,
    sheet_name="reports",
    engine="openpyxl"
)
print(adr.head(3))
print("Shape:", adr.shape)

  report_id  patient_age sex       drug              reaction  severity  \
0    ADR001         22.0   F    Aspirin             Dyspepsia      Mild   
1    ADR002         71.0   M   Warfarin              Bruising  Moderate   
2    ADR003         58.0   f  Metformin  Abdominal discomfort  Moderate   

  causality     outcome  
0  Possible   Recovered  
1  Probable  Recovering  
2  Possible   Recovered  
Shape: (40, 8)


### Explanation

io receives the Excel filename. sheet_name="reports" selects the worksheet that contains the ADR records. The DataFrame has 40 rows and 8 columns in the companion file.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-20"></a>

## 20. Worked Program 5: Import an ADR Excel Workbook

### Problem statement

Read the reports worksheet from adr_reports.xlsx and display the first three rows, shape, and column names.

### Objective

To practise pd.read_excel(), understand sheet_name, and verify the structure of an imported ADR table.

### Pharmacy context

The expected table contains 40 synthetic ADR reports and 8 variables. report_id is an identifier, patient_age is numeric with some intentionally missing values, and drug, reaction, severity, causality, and outcome are descriptive fields. This program verifies the table only; interpretation of missing and inconsistent entries is postponed to Chapter 11.

### Algorithm

1. Import Pandas.
2. Read adr_reports.xlsx with pd.read_excel().
3. Specify sheet_name="reports".
4. Store the result in adr.
5. Display the first three rows.
6. Display the shape and column names.

### Variables and parameters

| Variable / Parameter | Meaning | Example / Unit |
| --- | --- | --- |
| adr | Imported ADR DataFrame | 40 x 8 |
| io | Excel workbook passed to read_excel | adr_reports.xlsx |
| sheet_name | Worksheet selected from the workbook | reports |
| head(3) | Rows displayed for preview | 3 |
| shape | Rows and columns | (40, 8) |
| columns | Imported headers | 8 names |

### Code and executed output

The output appears directly below the code cell.

In [21]:
from pathlib import Path
import pandas as pd

adr_path = (DATA_DIR / "adr_reports.xlsx")
if not adr_path.exists():
    raise FileNotFoundError(
        "Place adr_reports.xlsx in the same folder as this notebook."
    )

adr = pd.read_excel(
    adr_path,
    sheet_name="reports",
    engine="openpyxl"
)

print(adr.head(3))
print("Shape:", adr.shape)
print("Columns:", list(adr.columns))

  report_id  patient_age sex       drug              reaction  severity  \
0    ADR001         22.0   F    Aspirin             Dyspepsia      Mild   
1    ADR002         71.0   M   Warfarin              Bruising  Moderate   
2    ADR003         58.0   f  Metformin  Abdominal discomfort  Moderate   

  causality     outcome  
0  Possible   Recovered  
1  Probable  Recovering  
2  Possible   Recovered  
Shape: (40, 8)
Columns: ['report_id', 'patient_age', 'sex', 'drug', 'reaction', 'severity', 'causality', 'outcome']


### Explanation

pd.read_excel() reads the selected worksheet into a DataFrame. sheet_name is critical when the workbook contains more than one sheet. The preview verifies that the intended table, not the data dictionary, has been loaded.

### Interpretation

The expected table contains 40 synthetic ADR reports and 8 variables. report_id is an identifier, patient_age is numeric with some intentionally missing values, and drug, reaction, severity, causality, and outcome are descriptive fields. This program verifies the table only; interpretation of missing and inconsistent entries is postponed to Chapter 11.

<a id="example-10-21"></a>

## 21. 10.15.1 head() - Preview the First Rows

### Problem statement

Demonstrate head() - Preview the First Rows using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support head() - preview the first rows and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.read_csv(DATA_DIR / 'pk_study.csv')` in `pk`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [22]:
import pandas as pd

pk = pd.read_csv(DATA_DIR / "pk_study.csv")
print(pk.head(3))

  subject_id  dose_mg  time_h  conc_ng_ml  age_years  weight_kg
0        S01      500     0.5        12.4         34       68.2
1        S01      500     1.0        88.6         34       68.2
2        S01      500     2.0       145.2         34       68.2


### Explanation

n=3 asks for three rows rather than the default five. A preview checks whether the expected headers and values appear in plausible columns without printing the entire dataset.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-22"></a>

## 22. 10.15.2 tail() - Preview the Last Rows

### Problem statement

Demonstrate tail() - Preview the Last Rows using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support tail() - preview the last rows and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.read_csv(DATA_DIR / 'pk_study.csv')` in `pk`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [23]:
import pandas as pd

pk = pd.read_csv(DATA_DIR / "pk_study.csv")
print(pk.tail(3))

   subject_id  dose_mg  time_h  conc_ng_ml  age_years  weight_kg
57        S12      250     2.0        78.4         31       63.5
58        S12      250     4.0        51.9         31       63.5
59        S12      250     8.0        22.5         31       63.5


### Explanation

n=3 returns the final three records. In the companion PK file these belong to the last subject at later time points, which is consistent with the dataset being ordered by subject and time.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-23"></a>

## 23. 10.15.3 shape - Count Rows and Columns

### Problem statement

Demonstrate shape - Count Rows and Columns using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support shape - count rows and columns and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.read_csv(DATA_DIR / 'pk_study.csv')` in `pk`.
3. Store `pd.read_excel(DATA_DIR / 'adr_reports.xlsx', sheet_name='reports', engine='openpyxl')` in `adr`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [24]:
import pandas as pd

pk = pd.read_csv(DATA_DIR / "pk_study.csv")
adr = pd.read_excel(
    DATA_DIR / "adr_reports.xlsx",
    sheet_name="reports",
    engine="openpyxl"
)

print("PK shape:", pk.shape)
print("ADR shape:", adr.shape)

PK shape: (60, 6)
ADR shape: (40, 8)


### Explanation

The first number counts rows and the second counts columns. These values are among the fastest ways to detect that the wrong sheet, wrong delimiter, or wrong file has been loaded.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-24"></a>

## 24. 10.15.4 columns - Read the Column Names

### Problem statement

Demonstrate columns - Read the Column Names using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support columns - read the column names and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.read_csv(DATA_DIR / 'pk_study.csv')` in `pk`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [25]:
import pandas as pd

pk = pd.read_csv(DATA_DIR / "pk_study.csv")
print(list(pk.columns))

['subject_id', 'dose_mg', 'time_h', 'conc_ng_ml', 'age_years', 'weight_kg']


### Explanation

The output shows the exact labels that must be used in later code. Spelling, case, spaces, and units matter. A surprising column name is a reason to inspect the source file before analysis.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-25"></a>

## 25. 10.15.5 dtypes - Check How Columns Were Read

### Problem statement

Demonstrate dtypes - Check How Columns Were Read using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support dtypes - check how columns were read and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.read_csv(DATA_DIR / 'pk_study.csv')` in `pk`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [26]:
import pandas as pd

pk = pd.read_csv(DATA_DIR / "pk_study.csv")
print(pk.dtypes)

subject_id     object
dose_mg         int64
time_h        float64
conc_ng_ml    float64
age_years       int64
weight_kg     float64
dtype: object


### Explanation

subject_id is text-like, dose_mg and age_years are integers, and time_h, conc_ng_ml, and weight_kg are floating point. This is a sensible structural result for the companion PK dataset.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-26"></a>

## 26. 10.15.6 info() - Structural Summary and Non-Null Counts

### Problem statement

Demonstrate info() - Structural Summary and Non-Null Counts using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support info() - structural summary and non-null counts and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.read_excel(DATA_DIR / 'adr_reports.xlsx', sheet_name='reports', engine='openpyxl')` in `adr`.
3. Execute `adr.info()`.

### Code and executed output

The output appears directly below the code cell.

In [27]:
import pandas as pd

adr = pd.read_excel(
    DATA_DIR / "adr_reports.xlsx",
    sheet_name="reports",
    engine="openpyxl"
)
adr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   report_id    40 non-null     object 
 1   patient_age  36 non-null     float64
 2   sex          40 non-null     object 
 3   drug         40 non-null     object 
 4   reaction     40 non-null     object 
 5   severity     38 non-null     object 
 6   causality    40 non-null     object 
 7   outcome      40 non-null     object 
dtypes: float64(1), object(7)
memory usage: 2.6+ KB


### Explanation

The ADR DataFrame has 40 rows and 8 columns. patient_age has 36 non-null values, so 4 ages are missing. severity has 38 non-null values, so 2 severity entries are missing. The text fields are displayed as object dtype in this environment. info() reveals the issue; Chapter 11 decides how to handle it.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-27"></a>

## 27. 10.15.7 describe() - Numeric Descriptive Summary

### Problem statement

Demonstrate describe() - Numeric Descriptive Summary using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support describe() - numeric descriptive summary and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.read_csv(DATA_DIR / 'pk_study.csv')` in `pk`.
3. Display the results for inspection.

### Important notes

The saved statistics have been recalculated from the supplied companion files. Some summary values printed in the source Word chapter differ from those files; the notebook reports the actual file-derived values.

### Code and executed output

The output appears directly below the code cell.

In [28]:
import pandas as pd

pk = pd.read_csv(DATA_DIR / "pk_study.csv")
print(pk[["dose_mg", "time_h", "conc_ng_ml",
          "age_years", "weight_kg"]]
      .describe()
      .round(1))

       dose_mg  time_h  conc_ng_ml  age_years  weight_kg
count     60.0    60.0        60.0       60.0       60.0
mean     375.0     3.1        58.0       37.2       70.8
std      126.1     2.8        41.7        6.7        6.0
min      250.0     0.5         5.6       28.0       61.9
25%      250.0     1.0        21.5       31.8       66.2
50%      375.0     2.0        47.0       36.5       70.0
75%      500.0     4.0        87.2       41.5       74.8
max      500.0     8.0       159.7       51.0       82.0


### Explanation

The result summarises the five numeric columns. count is 60 for each because the companion PK file has no missing values in these fields. The concentration statistics describe all subject-time observations together; they do not substitute for subject-level PK parameter estimation.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-28"></a>

## 28. 10.15.8 describe(include='object') - Text and Category Summary

### Problem statement

Demonstrate describe(include='object') - Text and Category Summary using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support describe(include='object') - text and category summary and interpret the result correctly.

### Pharmacy context

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

### Algorithm

1. Import `pandas`.
2. Store `pd.read_excel(DATA_DIR / 'adr_reports.xlsx', sheet_name='reports', engine='openpyxl')` in `adr`.
3. Display the results for inspection.

### Important notes

The saved statistics have been recalculated from the supplied companion files. Some summary values printed in the source Word chapter differ from those files; the notebook reports the actual file-derived values.

### Code and executed output

The output appears directly below the code cell.

In [29]:
import pandas as pd

adr = pd.read_excel(
    DATA_DIR / "adr_reports.xlsx",
    sheet_name="reports",
    engine="openpyxl"
)
print(adr[["sex", "drug", "reaction",
           "severity", "causality", "outcome"]]
      .describe(include="object"))

       sex     drug reaction  severity causality    outcome
count   40       40       40        38        40         40
unique   4        5       16         3         4          3
top      F  Aspirin   Nausea  Moderate  Possible  Recovered
freq    17        8        6        13        16         22


### Explanation

The text summary reports how many non-missing entries are present, how many distinct labels occur, and which value is most frequent. severity has a smaller count because two values are missing. If a category such as sex appears to have more unique labels than expected, the dataset should be examined before analysis.

### Interpretation

The PK table and ADR workbook are synthetic. Import and inspection establish the structure of the data; they do not establish its clinical validity or an ADR incidence rate.

<a id="example-10-29"></a>

## 29. Worked Program 6: Perform a First Inspection of the PK Dataset

### Problem statement

Import the PK CSV file and inspect its shape, first rows, last rows, column names, dtypes, info(), and descriptive statistics.

### Objective

To practise a disciplined first-look workflow for a time-course pharmaceutical dataset before analysis.

### Pharmacy context

The PK file contains 60 observations across 6 variables. Repeated subject IDs are expected because there are several time points per subject. time_h and conc_ng_ml are numeric, and no missing values are reported in this synthetic file. The overall concentration mean and quartiles describe all 60 time-point observations and should not be misinterpreted as Cmax, AUC, or a clinical threshold.

### Algorithm

1. Import Pandas.
2. Read pk_study.csv into pk.
3. Print the shape.
4. Display the first three and last three rows.
5. Display column names and dtypes.
6. Run info().
7. Run describe() on the numeric columns and round the output for readability.

### Variables and parameters

| Variable / Parameter | Meaning | Example / Unit |
| --- | --- | --- |
| pk | PK DataFrame | 60 x 6 |
| head(3) | First rows to display | 3 |
| tail(3) | Last rows to display | 3 |
| shape | Rows and columns | (60, 6) |
| columns | Header labels | 6 |
| dtypes | Storage type by column | object/int/float |
| info() | Non-null counts and dtypes | structural summary |
| describe() | Numeric statistics | count, mean, std, quartiles |

### Important notes

The saved statistics have been recalculated from the supplied companion files. Some summary values printed in the source Word chapter differ from those files; the notebook reports the actual file-derived values.

### Code and executed output

The output appears directly below the code cell.

In [30]:
from pathlib import Path
import pandas as pd

pk_path = (DATA_DIR / "pk_study.csv")
if not pk_path.exists():
    raise FileNotFoundError(
        "Place pk_study.csv in the same folder as this notebook."
    )

pk = pd.read_csv(pk_path)

print("Shape:", pk.shape)
print("\nFirst 3 rows:")
print(pk.head(3))
print("\nLast 3 rows:")
print(pk.tail(3))
print("\nColumns:", list(pk.columns))
print("\nDtypes:")
print(pk.dtypes)
print("\nInfo:")
pk.info()
print("\nNumeric summary:")
print(pk.describe().round(1))

Shape: (60, 6)

First 3 rows:
  subject_id  dose_mg  time_h  conc_ng_ml  age_years  weight_kg
0        S01      500     0.5        12.4         34       68.2
1        S01      500     1.0        88.6         34       68.2
2        S01      500     2.0       145.2         34       68.2

Last 3 rows:
   subject_id  dose_mg  time_h  conc_ng_ml  age_years  weight_kg
57        S12      250     2.0        78.4         31       63.5
58        S12      250     4.0        51.9         31       63.5
59        S12      250     8.0        22.5         31       63.5

Columns: ['subject_id', 'dose_mg', 'time_h', 'conc_ng_ml', 'age_years', 'weight_kg']

Dtypes:
subject_id     object
dose_mg         int64
time_h        float64
conc_ng_ml    float64
age_years       int64
weight_kg     float64
dtype: object

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   sub

### Explanation

The program follows one inspection sequence from broad structure to summary. It first confirms dimensions, then visually checks the beginning and end, then confirms names and types, and finally obtains non-null counts and descriptive statistics.

### Interpretation

The PK file contains 60 observations across 6 variables. Repeated subject IDs are expected because there are several time points per subject. time_h and conc_ng_ml are numeric, and no missing values are reported in this synthetic file. The overall concentration mean and quartiles describe all 60 time-point observations and should not be misinterpreted as Cmax, AUC, or a clinical threshold.

<a id="example-10-30"></a>

## 30. Worked Program 7: Inspect the ADR Workbook and Identify Structural Issues

### Problem statement

Read the reports worksheet and inspect the shape, first rows, column names, info(), and object-column describe() output.

### Objective

To use Pandas inspection tools to identify data-quality questions that should be addressed in the next chapter.

### Pharmacy context

The file contains 40 synthetic reports. patient_age has 36 non-null entries and severity has 38, revealing 4 missing ages and 2 missing severity values. Text columns also have multiple categories. These findings should be documented and then handled systematically in Chapter 11; students should not silently replace missing clinical-style data with zero or an arbitrary category.

### Algorithm

1. Import Pandas.
2. Read the reports worksheet from adr_reports.xlsx.
3. Display the shape and first three rows.
4. Display the column names.
5. Run info() to compare row count with non-null counts.
6. Run describe(include="object") on text columns.
7. Record the issues discovered without modifying the DataFrame.

### Variables and parameters

| Variable / Parameter | Meaning | Example / Unit |
| --- | --- | --- |
| adr | ADR DataFrame | 40 x 8 |
| sheet_name | Worksheet selected | reports |
| shape | Rows and columns | (40, 8) |
| info() | Non-null counts / dtypes | reveals missing values |
| describe(include="object") | Text summary | count, unique, top, freq |
| patient_age | Numeric field with missing entries | 36 non-null |
| severity | Text field with missing entries | 38 non-null |

### Important notes

The saved statistics have been recalculated from the supplied companion files. Some summary values printed in the source Word chapter differ from those files; the notebook reports the actual file-derived values.

### Code and executed output

The output appears directly below the code cell.

In [31]:
from pathlib import Path
import pandas as pd

adr_path = (DATA_DIR / "adr_reports.xlsx")
if not adr_path.exists():
    raise FileNotFoundError(
        "Place adr_reports.xlsx in the same folder as this notebook."
    )

adr = pd.read_excel(
    adr_path,
    sheet_name="reports",
    engine="openpyxl"
)

print("Shape:", adr.shape)
print(adr.head(3))
print("Columns:", list(adr.columns))

adr.info()

print(adr[["sex", "drug", "reaction", "severity",
           "causality", "outcome"]]
      .describe(include="object"))

Shape: (40, 8)
  report_id  patient_age sex       drug              reaction  severity  \
0    ADR001         22.0   F    Aspirin             Dyspepsia      Mild   
1    ADR002         71.0   M   Warfarin              Bruising  Moderate   
2    ADR003         58.0   f  Metformin  Abdominal discomfort  Moderate   

  causality     outcome  
0  Possible   Recovered  
1  Probable  Recovering  
2  Possible   Recovered  
Columns: ['report_id', 'patient_age', 'sex', 'drug', 'reaction', 'severity', 'causality', 'outcome']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   report_id    40 non-null     object 
 1   patient_age  36 non-null     float64
 2   sex          40 non-null     object 
 3   drug         40 non-null     object 
 4   reaction     40 non-null     object 
 5   severity     38 non-null     object 
 6   causality    40 non-null     object 

### Explanation

info() shows which columns have fewer non-null values than the total number of rows. describe(include="object") summarises the categorical fields. The output is evidence for later cleaning decisions, not a cleaning action by itself.

### Interpretation

The file contains 40 synthetic reports. patient_age has 36 non-null entries and severity has 38, revealing 4 missing ages and 2 missing severity values. Text columns also have multiple categories. These findings should be documented and then handled systematically in Chapter 11; students should not silently replace missing clinical-style data with zero or an arbitrary category.

<a id="example-10-31"></a>

## 31. Worked Program 8: Chapter 10 Integrated File-Inspection Workflow

### Problem statement

Read pk_study.csv and the reports sheet of adr_reports.xlsx, then perform a standard structural inspection of both DataFrames.

### Objective

To integrate Pandas installation assumptions, file import, DataFrame structure, and first-inspection methods in one beginner-level B.Pharm workflow.

### Pharmacy context

The PK DataFrame is complete in the supplied classroom file, whereas the ADR DataFrame contains missing entries that are visible in non-null counts. The program demonstrates a professional habit: identify and document structural issues before modifying data. Chapter 11 will use these findings to introduce missing-value treatment, duplicate handling, type correction, selection, filtering, sorting, grouping, aggregation, and clean export.

### Algorithm

1. Import Pandas.
2. Read the PK CSV file.
3. Read the ADR Excel reports sheet.
4. For the PK DataFrame, display shape, head, columns, dtypes, info, and numeric describe.
5. For the ADR DataFrame, display shape, head, columns, info, and object describe.
6. Write down the structural issues observed.
7. Stop before any cleaning action; carry those issues forward to Chapter 11.

### Variables and parameters

| Variable / Parameter | Meaning | Example / Unit |
| --- | --- | --- |
| pk | PK DataFrame | 60 x 6 |
| adr | ADR DataFrame | 40 x 8 |
| read_csv() | CSV reader | pk_study.csv |
| read_excel() | Excel reader | adr_reports.xlsx |
| sheet_name | Excel worksheet | reports |
| head(3) | Preview size | 3 rows |
| info() | Non-null + dtype report | both datasets |
| describe() | Numeric summary | PK |
| describe(include="object") | Text summary | ADR |

### Important notes

The saved statistics have been recalculated from the supplied companion files. Some summary values printed in the source Word chapter differ from those files; the notebook reports the actual file-derived values.

### Code and executed output

The output appears directly below the code cell.

In [32]:
from pathlib import Path
import pandas as pd

pk_path = (DATA_DIR / "pk_study.csv")
adr_path = (DATA_DIR / "adr_reports.xlsx")

if not pk_path.exists():
    raise FileNotFoundError(
        "Place pk_study.csv in the same folder as this notebook."
    )
if not adr_path.exists():
    raise FileNotFoundError(
        "Place adr_reports.xlsx in the same folder as this notebook."
    )

# 1. Read the files
pk = pd.read_csv(pk_path)
adr = pd.read_excel(
    adr_path,
    sheet_name="reports",
    engine="openpyxl"
)

# 2. Inspect the PK dataset
print("PK SHAPE:", pk.shape)
print(pk.head(3))
print("PK COLUMNS:", list(pk.columns))
print(pk.dtypes)
pk.info()
print(pk.describe().round(1))

# 3. Inspect the ADR dataset
print("ADR SHAPE:", adr.shape)
print(adr.head(3))
print("ADR COLUMNS:", list(adr.columns))
adr.info()
print(adr.describe(include="object"))

PK SHAPE: (60, 6)
  subject_id  dose_mg  time_h  conc_ng_ml  age_years  weight_kg
0        S01      500     0.5        12.4         34       68.2
1        S01      500     1.0        88.6         34       68.2
2        S01      500     2.0       145.2         34       68.2
PK COLUMNS: ['subject_id', 'dose_mg', 'time_h', 'conc_ng_ml', 'age_years', 'weight_kg']
subject_id     object
dose_mg         int64
time_h        float64
conc_ng_ml    float64
age_years       int64
weight_kg     float64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   subject_id  60 non-null     object 
 1   dose_mg     60 non-null     int64  
 2   time_h      60 non-null     float64
 3   conc_ng_ml  60 non-null     float64
 4   age_years   60 non-null     int64  
 5   weight_kg   60 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 2.9+ KB


### Explanation

The integrated program follows the same reproducible inspection logic for two different file formats. Pandas returns a DataFrame in both cases, so the same structural tools can be applied after the import step.

### Interpretation

The PK DataFrame is complete in the supplied classroom file, whereas the ADR DataFrame contains missing entries that are visible in non-null counts. The program demonstrates a professional habit: identify and document structural issues before modifying data. Chapter 11 will use these findings to introduce missing-value treatment, duplicate handling, type correction, selection, filtering, sorting, grouping, aggregation, and clean export.

## Review and practice

- Change one simulated input and predict the effect before rerunning the relevant cell.
- State the unit and meaning of each reported result.
- Explain one input condition or limitation that matters for the example.
- Restart the kernel and run all cells to check that the notebook is reproducible.

## Source and validation

Adapted from **Chapter_10_Data_Handling_with_Pandas_BPharm_Corrected_Executable.docx**. Worked programs and the complete code demonstrations are retained in chapter order. Installation commands are optional instructions; intentionally broken debugging examples are shown as corrected solutions. Notebook-specific changes are recorded in `Notebook_Guide_and_Validation.md`.