# Chapter 3: Operators and Program Logic

**B.Pharm companion Jupyter notebook — worked examples and concept demonstrations**

## Chapter focus

Apply arithmetic, comparisons, Boolean logic, assignment, membership and identity; use correct operator precedence and explicit parentheses.

## Pharmacy context

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

## Important notes and how to use this notebook

1. Use a Python 3 kernel. Read the problem and algorithm, predict the result, then run the cell with **Shift+Enter**.
2. Choose **Restart Kernel and Run All Cells** to reproduce the saved outputs. Run from top to bottom; later demonstrations may use earlier variables.
3. Outputs below code cells were produced by execution. Paths, versions, memory diagnostics and set display order can differ between computers.
4. All records are simulated for education. Retain units and distinguish a descriptive result from a clinical or regulatory decision.
5. Files written by examples are kept in `outputs/chapter_03`. Rerunning a file-writing example replaces its own generated output.
6. Input examples replay the printed sample entries by default. `classroom_input()` is a small teaching helper around Python's `input()`; select interactive mode to enter your own values.

These examples use the Python standard library; no external dataset is needed.


In [1]:
from pathlib import Path

WORKSHOP_ROOT = Path.cwd().resolve()
OUTPUT_DIR = WORKSHOP_ROOT / "outputs" / "chapter_03"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

import builtins
INTERACTIVE_INPUT = False

def classroom_input(prompt=""):
    """Read real input or replay this example's documented sample entries."""
    if INTERACTIVE_INPUT:
        return builtins.input(prompt)
    try:
        answer = next(_sample_answers)
    except StopIteration as error:
        raise RuntimeError("Sample entries exhausted. Review the algorithm or use interactive mode.") from error
    print(prompt + answer)
    return answer

print("Chapter 3 ready. Generated files: outputs/chapter_03")

Chapter 3 ready. Generated files: outputs/chapter_03


## Contents

- [01. 3.1.3.1 Pharmacy example: Arithmetic operators with input and type casting](#example-3-1)
- [02. 3.1.4.1 Pharmacy example: Comparison operators for stock checking](#example-3-2)
- [03. 3.1.5.1 Pharmacy example: Logical operators for temperature and expiry check](#example-3-3)
- [04. 3.1.6.1 Pharmacy example: Assignment operators for stock updating](#example-3-4)
- [05. 3.1.7.1 Pharmacy example: Membership operator for medicine availability](#example-3-5)
- [06. 3.1.7.2 Pharmacy example: Identity operator with missing test result](#example-3-6)
- [07. 3.1.7.3 Pharmacy example: Bitwise operator for beginner awareness](#example-3-7)
- [08. 3.1.8.1 Pharmacy example: Operator precedence in percentage strength calculation](#example-3-8)
- [09. 3.1.12.1 Program 3.1: Calculating total number of tablets](#example-3-9)
- [10. 3.1.12.2 Program 3.2: Checking storage temperature range](#example-3-10)
- [11. Algorithm:
Step 1: Store the opening stock.
Step 2: Store the received stock.
Step 3: Store the used stock.
Step 4: Add the received stock to the opening stock.
Step 5: Subtract the used stock from the updated stock.
Step 6: Store the result as final stock.
Step 7: Display the final stock.](#example-3-11)
- [12. 3.1.12.4 Program 3.4: Updating stock using assignment operators](#example-3-12)
- [13. 3.1.12.5 Program 3.5: Checking whether a medicine is in the stock list](#example-3-13)
- [14. 3.1.12.6 Program 3.6: Checking prescription quantity using combined conditions](#example-3-14)

<a id="example-3-1"></a>

## 01. 3.1.3.1 Pharmacy example: Arithmetic operators with input and type casting

### Problem statement

A pharmacy student needs to calculate the total daily dose when the dose per tablet and the number of doses per day are entered by the user.

### Objective

To use input, type casting and the multiplication operator to calculate the total daily dose for a simple educational pharmacy example.

### Pharmacy context

The output shows that 500 mg taken 3 times gives a calculated daily total of 1500.0 mg. From a pharmacy application point of view, this helps students understand how repeated dosing can be converted into a total daily quantity, but it should not be used as a clinical dose recommendation without professional validation.

### Algorithm

Step 1: Read the dose per tablet in milligrams.
 Step 2: Read the number of doses per day.
 Step 3: Convert the entered values into suitable numeric types.
 Step 4: Multiply the dose by the frequency.
 Step 5: Display the total daily dose.

### Important notes

Saved output uses these sample entries in order: `500`, `3`. Set INTERACTIVE_INPUT = True in the setup cell to type your own entries.

### Code and executed output

The output appears directly below the code cell.

In [2]:
_sample_answers = iter(['500', '3'])

dose_mg = float(classroom_input("Enter dose per tablet in mg: "))
frequency = int(classroom_input("Enter number of doses per day: "))
daily_dose = dose_mg * frequency
print("Total daily dose:", daily_dose, "mg")

Enter dose per tablet in mg: 500
Enter number of doses per day: 3
Total daily dose: 1500.0 mg


### Explanation

The input() function reads values as text. The float() function changes the dose into a decimal number, and int() changes the frequency into a whole number. The multiplication operator calculates the total daily dose for classroom practice.

### Interpretation

The output shows that 500 mg taken 3 times gives a calculated daily total of 1500.0 mg. From a pharmacy application point of view, this helps students understand how repeated dosing can be converted into a total daily quantity, but it should not be used as a clinical dose recommendation without professional validation.

<a id="example-3-2"></a>

## 02. 3.1.4.1 Pharmacy example: Comparison operators for stock checking

### Problem statement

A pharmacy store needs to check whether the current quantity of a medicine has reached or fallen below the reorder level.

### Objective

To apply a comparison operator and obtain a Boolean result that indicates whether reordering is required.

### Pharmacy context

The output is True because the current stock is 35 and the reorder level is 40. From a pharmacy inventory point of view, this indicates that the medicine quantity has reached the reorder threshold and should be considered for replenishment according to store policy.

### Algorithm

Step 1: Enter the current stock.
 Step 2: Enter the reorder level.
 Step 3: Convert both values into integers.
 Step 4: Compare the current stock with the reorder level using the less than or equal to operator.
 Step 5: Display True if reordering is needed; otherwise, display False.

### Important notes

Saved output uses these sample entries in order: `35`, `40`. Set INTERACTIVE_INPUT = True in the setup cell to type your own entries.

### Code and executed output

The output appears directly below the code cell.

In [3]:
_sample_answers = iter(['35', '40'])

current_stock = int(classroom_input("Enter current stock: "))
reorder_level = int(classroom_input("Enter reorder level: "))
needs_reorder = current_stock <= reorder_level
print("Reorder needed:", needs_reorder)

Enter current stock: 35
Enter reorder level: 40
Reorder needed: True


### Explanation

The int() function converts text input into whole numbers. The comparison operator <= checks whether the current stock is less than or equal to the reorder level. The result is a Boolean value, either True or False.

### Interpretation

The output is True because the current stock is 35 and the reorder level is 40. From a pharmacy inventory point of view, this indicates that the medicine quantity has reached the reorder threshold and should be considered for replenishment according to store policy.

<a id="example-3-3"></a>

## 03. 3.1.5.1 Pharmacy example: Logical operators for temperature and expiry check

### Problem statement

A refrigerated medicine must be checked for two conditions: whether the temperature is within the recommended range and whether the medicine is not expired.

### Objective

To combine comparison and logical operators so that multiple pharmacy-related conditions can be evaluated together.

### Pharmacy context

The output is True because the entered temperature is 6°C, which lies between 2°C and 8°C, and the medicine is marked as not expired. In pharmacy practice, such a result supports the idea that both storage condition and expiry status must be checked together before accepting a medicine as suitable for use or storage.

### Algorithm

Step 1: Enter the refrigerator temperature.
Step 2: Enter whether the medicine is expired.
Step 3: Check whether the temperature is between 2°C and 8°C.
Step 4: Check that the medicine is not expired.
Step 5: Combine all conditions using logical operators.
Step 6: Display whether the storage condition is acceptable for this classroom example.

### Important notes

Saved output uses these sample entries in order: `6`, `False`. Set INTERACTIVE_INPUT = True in the setup cell to type your own entries.

### Code and executed output

The output appears directly below the code cell.

In [4]:
_sample_answers = iter(['6', 'False'])

temperature = float(classroom_input("Enter refrigerator temperature: "))
is_expired = classroom_input("Is the medicine expired? Type True or False: ") == "True"
safe_to_store = temperature >= 2 and temperature <= 8 and not is_expired
print("Safe to store:", safe_to_store)

Enter refrigerator temperature: 6
Is the medicine expired? Type True or False: False
Safe to store: True


### Explanation

This program combines three conditions. The medicine is considered safe for this classroom example only when the temperature is between 2°C and 8°C and the medicine is not expired.

### Interpretation

The output is True because the entered temperature is 6°C, which lies between 2°C and 8°C, and the medicine is marked as not expired. In pharmacy practice, such a result supports the idea that both storage condition and expiry status must be checked together before accepting a medicine as suitable for use or storage.

<a id="example-3-4"></a>

## 04. 3.1.6.1 Pharmacy example: Assignment operators for stock updating

### Problem statement

A pharmacy store records opening stock, newly received stock and issued stock. The program must update the final stock using assignment operators.

### Objective

To demonstrate how assignment operators such as += and -= help update inventory values without rewriting long expressions.

### Pharmacy context

The final stock is 66 because the opening stock of 60 first increases by 20 received units and then decreases by 14 issued units. In a pharmacy setting, this type of program helps learners understand simple inventory movement, though actual pharmacy stock systems also require batch number, expiry date and audit records.

### Algorithm

Step 1: Read the opening stock.
 Step 2: Read the received quantity.
 Step 3: Read the issued quantity.
 Step 4: Add the received quantity to stock using +=.
 Step 5: Subtract the issued quantity using -=.
 Step 6: Display the final stock.

### Important notes

Saved output uses these sample entries in order: `60`, `20`, `14`. Set INTERACTIVE_INPUT = True in the setup cell to type your own entries.

### Code and executed output

The output appears directly below the code cell.

In [5]:
_sample_answers = iter(['60', '20', '14'])

stock = int(classroom_input("Enter opening stock: "))
received = int(classroom_input("Enter received stock: "))
issued = int(classroom_input("Enter issued stock: "))
stock += received
stock -= issued
print("Final stock:", stock)

Enter opening stock: 60
Enter received stock: 20
Enter issued stock: 14
Final stock: 66


### Explanation

The variable stock first stores the opening stock. The operator += adds received stock, and -= subtracts issued stock. This is a simple way to update pharmacy inventory values.

### Interpretation

The final stock is 66 because the opening stock of 60 first increases by 20 received units and then decreases by 14 issued units. In a pharmacy setting, this type of program helps learners understand simple inventory movement, though actual pharmacy stock systems also require batch number, expiry date and audit records.

<a id="example-3-5"></a>

## 05. 3.1.7.1 Pharmacy example: Membership operator for medicine availability

### Problem statement

A learner wants to check whether a medicine entered by the user is present in the available medicine list.

### Objective

To use the membership operator in to test whether a medicine name exists in a list.

### Pharmacy context

The output is True because Cetirizine is present in the available medicine list. From a pharmacy application point of view, this demonstrates the basic idea behind checking availability, although real pharmacy software would also check strength, dosage form, batch, expiry and stock quantity.

### Algorithm

Step 1: Create a list of available medicines.
 Step 2: Ask the user to enter a medicine name.
 Step 3: Use the in operator to check list membership.
 Step 4: Store the result as True or False.
 Step 5: Display whether the medicine is available.

### Important notes

Saved output uses these sample entries in order: `Cetirizine`. Set INTERACTIVE_INPUT = True in the setup cell to type your own entries.

### Code and executed output

The output appears directly below the code cell.

In [6]:
_sample_answers = iter(['Cetirizine'])

available_medicines = ["Paracetamol", "Cetirizine", "Amoxicillin"]
medicine_name = classroom_input("Enter medicine name: ")
is_available = medicine_name in available_medicines
print("Medicine available:", is_available)

Enter medicine name: Cetirizine
Medicine available: True


### Explanation

The membership operator in checks whether the entered medicine name is present in the list. The output is True when the medicine exists in the list and False when it does not.

### Interpretation

The output is True because Cetirizine is present in the available medicine list. From a pharmacy application point of view, this demonstrates the basic idea behind checking availability, although real pharmacy software would also check strength, dosage form, batch, expiry and stock quantity.

<a id="example-3-6"></a>

## 06. 3.1.7.2 Pharmacy example: Identity operator with missing test result

### Problem statement

A sample has no assay result recorded yet, and the program must check whether the result is missing.

### Objective

To use the identity operator is to check whether a variable contains the value None.

### Pharmacy context

The output is True because assay_result currently contains None. In a pharmacy quality-control context, this reminds learners that missing results must be identified before any conclusion is drawn from data.

### Algorithm

Step 1: Store None in the assay result variable to represent missing data.
 Step 2: Use is None to test whether the value is missing.
 Step 3: Store the Boolean result.
 Step 4: Display whether the assay result is missing.

### Code and executed output

The output appears directly below the code cell.

In [7]:
assay_result = None
result_missing = assay_result is None
print("Assay result missing:", result_missing)

Assay result missing: True


### Explanation

The value None is used when data are not recorded or not available. The identity operator is checks whether assay_result is exactly None.

### Interpretation

The output is True because assay_result currently contains None. In a pharmacy quality-control context, this reminds learners that missing results must be identified before any conclusion is drawn from data.

<a id="example-3-7"></a>

## 07. 3.1.7.3 Pharmacy example: Bitwise operator for beginner awareness

### Problem statement

Two simple flag values are used to demonstrate how bitwise AND and bitwise OR produce different results.

### Objective

To introduce bitwise operators at a basic awareness level so that learners can recognise them when reading Python reference material.

### Pharmacy context

Bitwise AND gives 0 because both flag values are not 1, while bitwise or gives 1 because at least one flag value is 1. For pharmacy beginners, this example should be treated as conceptual awareness rather than a routine calculation method.

### Algorithm

Step 1: Store the first flag value.
 Step 2: Store the second flag value.
 Step 3: Apply bitwise AND.
 Step 4: Apply bitwise OR.
 Step 5: Display both results for comparison.

### Code and executed output

The output appears directly below the code cell.

In [8]:
flag_a = 1
flag_b = 0
print("Bitwise AND:", flag_a & flag_b)
print("Bitwise OR:", flag_a | flag_b)

Bitwise AND: 0
Bitwise OR: 1


### Explanation

Bitwise operators work with binary values. They are not normally required for beginner pharmacy calculations, but students should recognise them when they appear in Python reference material.

### Interpretation

Bitwise AND gives 0 because both flag values are not 1, while bitwise or gives 1 because at least one flag value is 1. For pharmacy beginners, this example should be treated as conceptual awareness rather than a routine calculation method.

<a id="example-3-8"></a>

## 08. 3.1.8.1 Pharmacy example: Operator precedence in percentage strength calculation

### Problem statement

A student needs to calculate the percentage strength of a solution using drug mass and solution volume, while ensuring that the expression is evaluated in the correct order.

### Objective

To demonstrate the importance of parentheses in percentage strength calculations and to avoid confusion caused by operator precedence.

### Pharmacy context

The output shows a strength of 0.25% w/v because 250 mg is first converted to 0.25 g, then divided by 100 mL, and finally multiplied by 100. From a pharmacy application point of view, this reinforces that unit conversion and correct order of operations are essential before interpreting any calculated formulation value.

### Algorithm

1. Store `iter(['250', '100'])` in `_sample_answers`.
2. Store `float(classroom_input('Enter drug mass in mg: '))` in `drug_mass_mg`.
3. Store `float(classroom_input('Enter solution volume in mL: '))` in `solution_volume_ml`.
4. Store `drug_mass_mg / 1000` in `drug_mass_g`.
5. Store `drug_mass_g / solution_volume_ml * 100` in `strength_percent`.
6. Display the results for inspection.

### Important notes

Saved output uses these sample entries in order: `250`, `100`. Set INTERACTIVE_INPUT = True in the setup cell to type your own entries.

### Code and executed output

The output appears directly below the code cell.

In [9]:
_sample_answers = iter(['250', '100'])

drug_mass_mg = float(classroom_input("Enter drug mass in mg: "))
solution_volume_ml = float(classroom_input("Enter solution volume in mL: "))
drug_mass_g = drug_mass_mg / 1000
strength_percent = (drug_mass_g / solution_volume_ml) * 100
print("Strength:", strength_percent, "% w/v")

Enter drug mass in mg: 250
Enter solution volume in mL: 100
Strength: 0.25 % w/v


### Explanation

The mass is first converted from milligrams to grams. Division and multiplication have equal precedence and group from left to right. The parentheses make the intended percentage-strength calculation explicit; the result is unchanged without them in this expression.

### Interpretation

The output shows a strength of 0.25% w/v because 250 mg is first converted to 0.25 g, then divided by 100 mL, and finally multiplied by 100. From a pharmacy application point of view, this reinforces that unit conversion and correct order of operations are essential before interpreting any calculated formulation value.

<a id="example-3-9"></a>

## 09. 3.1.12.1 Program 3.1: Calculating total number of tablets

### Problem statement

Calculate the total number of tablets when the number of tablets in one strip and the number of strips are known.

### Objective

To use the multiplication operator to calculate total tablets from tablets per strip and number of strips.

### Pharmacy context

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

### Algorithm

Step 1: Store the number of tablets in one strip.
Step 2: Store the number of strips.
Step 3: Multiply tablets per strip by the number of strips.
Step 4: Store the result as total tablets.
Step 5: Display the total number of tablets

### Code and executed output

The output appears directly below the code cell.

In [10]:
tablets_per_strip = 10
number_of_strips = 5
total_tablets = tablets_per_strip * number_of_strips
print(total_tablets)

50


### Explanation

The program stores the number of tablets in one strip and the number of strips in two variables. The multiplication operator * multiplies both values. The result is stored in total_tablets and then displayed using print().

### Interpretation

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

<a id="example-3-10"></a>

## 10. 3.1.12.2 Program 3.2: Checking storage temperature range

### Problem statement

Check whether a refrigerator temperature is within the required classroom range of 2°C to 8°C.

### Objective

To use comparison operators and the logical operator and to test whether a temperature falls within a specified range.

### Pharmacy context

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

### Algorithm

Step 1: Store the refrigerator temperature.
Step 2: Check whether the temperature is greater than or equal to 2°C.
Step 3: Check whether the temperature is less than or equal to 8°C.
Step 4: Combine both conditions using the logical operator and.
Step 5: Store the result as a Boolean value.
Step 6: Display the result.

### Code and executed output

The output appears directly below the code cell.

In [11]:
temperature = 6
is_within_range = temperature >= 2 and temperature <= 8
print(is_within_range)

True


### Explanation

The first comparison checks whether the temperature is at least 2°C. The second comparison checks whether the temperature is not above 8°C. The logical operator and gives True only when both comparisons are true.

### Interpretation

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

<a id="example-3-11"></a>

## 11. Algorithm:
Step 1: Store the opening stock.
Step 2: Store the received stock.
Step 3: Store the used stock.
Step 4: Add the received stock to the opening stock.
Step 5: Subtract the used stock from the updated stock.
Step 6: Store the result as final stock.
Step 7: Display the final stock.

### Problem statement

Demonstrate algorithm:
Step 1: Store the opening stock.
Step 2: Store the received stock.
Step 3: Store the used stock.
Step 4: Add the received stock to the opening stock.
Step 5: Subtract the used stock from the updated stock.
Step 6: Store the result as final stock.
Step 7: Display the final stock. using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support algorithm:
step 1: store the opening stock.
step 2: store the received stock.
step 3: store the used stock.
step 4: add the received stock to the opening stock.
step 5: subtract the used stock from the updated stock.
step 6: store the result as final stock.
step 7: display the final stock. and interpret the result correctly.

### Pharmacy context

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

### Algorithm

Step 1: Store the opening stock.
Step 2: Store the received stock.
Step 3: Store the used stock.
Step 4: Add the received stock to the opening stock.
Step 5: Subtract the used stock from the updated stock.
Step 6: Store the result as final stock.
Step 7: Display the final stock.

### Code and executed output

The output appears directly below the code cell.

In [12]:
opening_stock = 25
received_stock = 10
used_stock = 8
final_stock = opening_stock + received_stock - used_stock
print("Final stock:", final_stock)

Final stock: 27


### Explanation

The program first adds the received stock to the opening stock. It then subtracts the used stock. The final value represents the remaining quantity after both stock movements have been considered.

### Interpretation

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

<a id="example-3-12"></a>

## 12. 3.1.12.4 Program 3.4: Updating stock using assignment operators

### Problem statement

Update medicine stock by adding received stock and subtracting issued stock using assignment operators.

### Objective

Understand how the Python operations in this example support program 3.4: updating stock using assignment operators and interpret the result correctly.

### Pharmacy context

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

### Algorithm

Step 1: Store the opening stock.
Step 2: Add received stock using the assignment operator +=.
Step 3: Subtract issued stock using the assignment operator -=.
Step 4: Store the updated value as available stock.
Step 5: Display the available stock.

### Code and executed output

The output appears directly below the code cell.

In [13]:
stock = 40
stock += 15
stock -= 8
print("Available stock:", stock)

Available stock: 47


### Explanation

The operator += increases the current value of stock by 15. The operator -= then decreases the updated stock value by 8. The final value is displayed as available stock.

### Interpretation

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

<a id="example-3-13"></a>

## 13. 3.1.12.5 Program 3.5: Checking whether a medicine is in the stock list

### Problem statement

Check whether a given medicine is present in the available stock list.

### Objective

Understand how the Python operations in this example support program 3.5: checking whether a medicine is in the stock list and interpret the result correctly.

### Pharmacy context

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

### Algorithm

Step 1: Create a list of available medicines.
Step 2: Store the medicine name to be checked.
Step 3: Use the membership operator in to check whether the medicine is present in the list.
Step 4: Store the result as a Boolean value.
Step 5: Display whether the medicine is available.

### Code and executed output

The output appears directly below the code cell.

In [14]:
medicine_list = ["Paracetamol", "Cetirizine", "Amoxicillin"]
medicine = "Paracetamol"
available = medicine in medicine_list
print(available)

True


### Explanation

The list stores the available medicines. The membership operator in checks whether the selected medicine is present in the list. Since Paracetamol is present, the result is True.

### Interpretation

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

<a id="example-3-14"></a>

## 14. 3.1.12.6 Program 3.6: Checking prescription quantity using combined conditions

### Problem statement

Check whether the prescribed quantity of tablets is valid by ensuring that it is positive and does not exceed the available stock.

### Objective

Understand how the Python operations in this example support program 3.6: checking prescription quantity using combined conditions and interpret the result correctly.

### Pharmacy context

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

### Algorithm

Step 1: Store the prescribed number of tablets.
Step 2: Store the available number of tablets.
Step 3: Check whether the prescribed quantity is greater than zero.
Step 4: Check whether the prescribed quantity is less than or equal to the available quantity.
Step 5: Combine both conditions using the logical operator and.
Step 6: Store the final result as a Boolean value.
Step 7: Display the final result.

### Code and executed output

The output appears directly below the code cell.

In [15]:
prescribed_tablets = 30
available_tablets = 50
valid_quantity = prescribed_tablets > 0 and prescribed_tablets <= available_tablets
print(valid_quantity)

True


### Explanation

The first condition checks whether the prescribed quantity is positive. The second condition checks whether the required quantity does not exceed the available stock. Since both conditions are true, the logical operator “and” returns True.

### Interpretation

Operators support inventory calculations, storage-condition checks and formulation arithmetic. Conditions and dose examples use simulated values; they do not authorize dispensing or establish product suitability.

## Operator precedence: verified examples

**Problem:** Predict calculations that combine powers, unary signs, multiplication, addition, comparisons and Boolean operations.

**Pharmacy context:** Parentheses make classroom formulation and stock calculations easier to audit.

**Algorithm:** Evaluate explicit parentheses first; apply Python precedence; compare the output with the predicted value. Power is right-associative. Unary minus to the left of a power is applied after that power; a signed exponent is allowed on the right.

Highest to lowest among these operators: `**`; unary `+ - ~`; `* / // % @`; `+ -`; `<< >>`; `&`; `^`; `|`; comparisons (including membership and identity); `not`; `and`; `or`. Parentheses control grouping. Assignment statements are not a level in this expression-precedence list.

In [16]:
print("2 + 3 * 4 =", 2 + 3 * 4)
print("(2 + 3) * 4 =", (2 + 3) * 4)
print("2 ** 3 ** 2 =", 2 ** 3 ** 2)
print("-2 ** 2 =", -2 ** 2)
print("(-2) ** 2 =", (-2) ** 2)
print("2 ** -2 =", 2 ** -2)
print("2 <= 6 <= 8 =", 2 <= 6 <= 8)
print("not False and True or False =", not False and True or False)

2 + 3 * 4 = 14
(2 + 3) * 4 = 20
2 ** 3 ** 2 = 512
-2 ** 2 = -4
(-2) ** 2 = 4
2 ** -2 = 0.25
2 <= 6 <= 8 = True
not False and True or False = True


**Explanation:** The results are 14, 20, 512, −4, 4, 0.25, True and True. Powers associate to the right. Comparisons can chain; `not` binds more tightly than `and`, which binds more tightly than `or`.

## Review and practice

- Change one simulated input and predict the effect before rerunning the relevant cell.
- State the unit and meaning of each reported result.
- Explain one input condition or limitation that matters for the example.
- Restart the kernel and run all cells to check that the notebook is reproducible.

## Source and validation

Adapted from **2992_03_Final_KS_Corrected.docx**. Worked programs and the complete code demonstrations are retained in chapter order. Installation commands are optional instructions; intentionally broken debugging examples are shown as corrected solutions. Notebook-specific changes are recorded in `Notebook_Guide_and_Validation.md`.