# Chapter 2: Variables, Data Types, Type Casting, Operators and Input/Output Operations

**B.Pharm companion Jupyter notebook — worked examples and concept demonstrations**

## Chapter focus

Represent pharmaceutical values using appropriate Python types; understand assignment, identity and mutability; convert input and format output.

## Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

## Important notes and how to use this notebook

1. Use a Python 3 kernel. Read the problem and algorithm, predict the result, then run the cell with **Shift+Enter**.
2. Choose **Restart Kernel and Run All Cells** to reproduce the saved outputs. Run from top to bottom; later demonstrations may use earlier variables.
3. Outputs below code cells were produced by execution. Paths, versions, memory diagnostics and set display order can differ between computers.
4. All records are simulated for education. Retain units and distinguish a descriptive result from a clinical or regulatory decision.
5. Files written by examples are kept in `outputs/chapter_02`. Rerunning a file-writing example replaces its own generated output.
6. Input examples replay the printed sample entries by default. `classroom_input()` is a small teaching helper around Python's `input()`; select interactive mode to enter your own values.

These examples use the Python standard library; no external dataset is needed.


In [1]:
from pathlib import Path

WORKSHOP_ROOT = Path.cwd().resolve()
OUTPUT_DIR = WORKSHOP_ROOT / "outputs" / "chapter_02"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

import builtins
INTERACTIVE_INPUT = False

def classroom_input(prompt=""):
    """Read real input or replay this example's documented sample entries."""
    if INTERACTIVE_INPUT:
        return builtins.input(prompt)
    try:
        answer = next(_sample_answers)
    except StopIteration as error:
        raise RuntimeError("Sample entries exhausted. Review the algorithm or use interactive mode.") from error
    print(prompt + answer)
    return answer

print("Chapter 2 ready. Generated files: outputs/chapter_02")

Chapter 2 ready. Generated files: outputs/chapter_02


## Contents

- [01. 2.2.1 Definition and the assignment statement](#example-2-1)
- [02. 2.2.3 Object identity and the id() function](#example-2-2)
- [03. 2.2.4 Rules for naming variables](#example-2-3)
- [04. 2.2.6.1 Multiple assignment to a single value](#example-2-4)
- [05. 2.2.6.2 Parallel assignment and tuple unpacking](#example-2-5)
- [06. 2.2.6.3 Exchanging the values of two variables](#example-2-6)
- [07. 2.2.6.4 Augmented assignment](#example-2-7)
- [08. 2.2.7 Dynamic typing and rebinding](#example-2-8)
- [09. 2.2.8 Mutability and immutability](#example-2-9)
- [10. 2.2.8 Mutability and immutability](#example-2-10)
- [11. 2.2.8 Mutability and immutability](#example-2-11)
- [12. 2.2.8 Mutability and immutability](#example-2-12)
- [13. 2.2.9 Object lifetime, reference counting and garbage collection](#example-2-13)
- [14. 2.2.10 Deleting a name](#example-2-14)
- [15. 2.3.2 Integers (int)](#example-2-15)
- [16. 2.3.2 Integers (int)](#example-2-16)
- [17. 2.3.3 Floating-point numbers (float)](#example-2-17)
- [18. 2.3.3.1 The limits of floating-point precision](#example-2-18)
- [19. 2.3.3.1 The limits of floating-point precision](#example-2-19)
- [20. 2.3.4 Complex numbers (complex)](#example-2-20)
- [21. 2.3.5 Boolean values (bool)](#example-2-21)
- [22. 2.3.5 Boolean values (bool)](#example-2-22)
- [23. 2.3.6 Strings (str)](#example-2-23)
- [24. 2.3.6 Strings (str)](#example-2-24)
- [25. 2.3.7 Byte strings (bytes)](#example-2-25)
- [26. 2.3.8 Lists (list)](#example-2-26)
- [27. 2.3.9 Tuples (tuple)](#example-2-27)
- [28. 2.3.9 Tuples (tuple)](#example-2-28)
- [29. 2.3.10 Sets and frozen sets (set, frozenset)](#example-2-29)
- [30. 2.3.11 Dictionaries (dict)](#example-2-30)
- [31. 2.3.12 Null object (NoneType)](#example-2-31)
- [32. 2.3.14 Determining the type: type() and isinstance()](#example-2-32)
- [33. 2.3.14 Determining the type: type() and isinstance()](#example-2-33)
- [34. 2.4.2 Implicit type conversion](#example-2-34)
- [35. 2.4.2 Implicit type conversion](#example-2-35)
- [36. 2.4.3.1 Conversion to an integer: int()](#example-2-36)
- [37. 2.4.3.2 Conversion to a floating-point number: float()](#example-2-37)
- [38. 2.4.3.3 Conversion to a string: str()](#example-2-38)
- [39. 2.4.3.4 Conversion to a Boolean: bool()](#example-2-39)
- [40. 2.4.3.4 Conversion to a Boolean: bool()](#example-2-40)
- [41. 2.4.3.5 Conversion between collection types](#example-2-41)
- [42. 2.4.3.6 Conversion between numeric representations](#example-2-42)
- [43. 2.4.4 Loss of precision in conversion](#example-2-43)
- [44. 2.4.4 Loss of precision in conversion](#example-2-44)
- [45. 2.4.4 Loss of precision in conversion](#example-2-45)
- [46. 2.4.5 Errors arising from invalid conversion](#example-2-46)
- [47. 2.4.5 Errors arising from invalid conversion](#example-2-47)
- [48. 2.4.5 Errors arising from invalid conversion](#example-2-48)
- [49. 2.4.5 Errors arising from invalid conversion](#example-2-49)
- [50. 2.5.1 The input() function](#example-2-50)
- [51. 2.5.1 The input() function](#example-2-51)
- [52. 2.5.1.1 Reading numeric values](#example-2-52)
- [53. 2.5.1.2 Reading several values from one line](#example-2-53)
- [54. 2.5.2.1 Displaying objects](#example-2-54)
- [55. 2.5.2.2 The sep argument](#example-2-55)
- [56. 2.5.2.3 The end argument](#example-2-56)
- [57. 2.5.2.3 The end argument](#example-2-57)
- [58. 2.5.2.4 The file argument](#example-2-58)
- [59. 2.5.2.5 The flush argument](#example-2-59)
- [60. 2.5.3 Escape sequences](#example-2-60)
- [61. 2.5.4.1 Percentage formatting](#example-2-61)
- [62. 2.5.4.2 The str.format() method](#example-2-62)
- [63. 2.5.4.3 Formatted string literals (f-strings)](#example-2-63)
- [64. 2.5.4.4 The format specification](#example-2-64)
- [65. 2.5.5 Rounding for display compared with rounding of values](#example-2-65)

<a id="example-2-1"></a>

## 01. 2.2.1 Definition and the assignment statement

### Problem statement

Demonstrate definition and the assignment statement using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support definition and the assignment statement and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `'Amoxicillin'` in `drug_name`.
2. Store `500` in `strength_mg`.
3. Store `2.5` in `concentration_mg_ml`.
4. Store `True` in `is_refrigerated`.
5. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [2]:
drug_name = "Amoxicillin"
strength_mg = 500
concentration_mg_ml = 2.5
is_refrigerated = True
 
print(drug_name)
print(strength_mg)
print(concentration_mg_ml)
print(is_refrigerated)

Amoxicillin
500
2.5
True


### Explanation

The use of variables confers three practical advantages. First, a value that appears repeatedly in a calculation need be written only once, which reduces transcription error. Second, a descriptive name such as strength_mg documents the meaning and the unit of the quantity, whereas the bare numeral 500 documents nothing. Third, when a value must be changed, the alteration is made in one place only.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-2"></a>

## 02. 2.2.3 Object identity and the id() function

### Problem statement

Demonstrate object identity and the id() function using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support object identity and the id() function and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `'B2401A'` in `batch_a`.
2. Store `batch_a` in `batch_b`.
3. Display the results for inspection.
4. Store `'B2401'` in `batch_prefix`.
5. Store `batch_prefix + 'A'` in `batch_c`.
6. Display the results for inspection.

### Important notes

Use == for value equality and is for identity. String interning and constant reuse are implementation details; never rely on identity tests to compare medicine names or batch-code values.

### Code and executed output

The output appears directly below the code cell.

In [3]:
batch_a = "B2401A"
batch_b = batch_a              # a second name for the same object
print(batch_a is batch_b)      # same object?
 
batch_prefix = "B2401"
batch_c = batch_prefix + "A"   # a newly constructed object
print(batch_a == batch_c)      # equal value?
print(batch_a is batch_c)      # same object?

True
True
False


### Explanation

The output demonstrates that batch_a and batch_c hold equal values but are distinct objects. The assignment batch_b = batch_a created no new object whatsoever; it merely recorded a second name referring to the existing one.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-3"></a>

## 03. 2.2.4 Rules for naming variables

### Problem statement

Demonstrate rules for naming variables using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support rules for naming variables and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Import `keyword`.
2. Display the results for inspection.

### Important notes

The keyword list depends on the Python version; soft keywords are reported separately by keyword.softkwlist in versions that support them.

### Code and executed output

The output appears directly below the code cell.

In [4]:
import keyword
 
print(len(keyword.kwlist))
print(keyword.kwlist)

35
['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


### Explanation

Python 3 reserves thirty-five keywords. Their number and membership may be confirmed at any time by importing the keyword module, which is useful because the list has changed between versions of the language.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-4"></a>

## 04. 2.2.6.1 Multiple assignment to a single value

### Problem statement

Demonstrate multiple assignment to a single value using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support multiple assignment to a single value and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `0` in `sample_1, sample_2, sample_3`.
2. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [5]:
sample_1 = sample_2 = sample_3 = 0
 
print(sample_1, sample_2, sample_3)
print(id(sample_1) == id(sample_2) == id(sample_3))

0 0 0
True


### Explanation

A single object may be bound to several names in one statement. All the names refer to the same object, as the identity test confirms.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-5"></a>

## 05. 2.2.6.2 Parallel assignment and tuple unpacking

### Problem statement

Demonstrate parallel assignment and tuple unpacking using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support parallel assignment and tuple unpacking and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `(62.5, 1.68)` in `(body_weight_kg, height_m)`.
2. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [6]:
body_weight_kg, height_m = 62.5, 1.68
 
print("Weight:", body_weight_kg, "kg")
print("Height:", height_m, "m")

Weight: 62.5 kg
Height: 1.68 m


### Explanation

Several names may be bound to several values in a single statement. The values on the right are evaluated first, and are then distributed to the names on the left in order. The number of names must equal the number of values.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-6"></a>

## 06. 2.2.6.3 Exchanging the values of two variables

### Problem statement

Demonstrate exchanging the values of two variables using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support exchanging the values of two variables and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `(505.0, 495.0)` in `(lower_limit_mg, upper_limit_mg)`.
2. Display the results for inspection.
3. Store `(upper_limit_mg, lower_limit_mg)` in `(lower_limit_mg, upper_limit_mg)`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [7]:
lower_limit_mg, upper_limit_mg = 505.0, 495.0    # entered in the wrong order
 
print("Before ->", lower_limit_mg, upper_limit_mg)
 
lower_limit_mg, upper_limit_mg = upper_limit_mg, lower_limit_mg
print("After  ->", lower_limit_mg, upper_limit_mg)

Before -> 505.0 495.0
After  -> 495.0 505.0


### Explanation

Because the right-hand side is evaluated in its entirety before any name is rebound, two variables may be exchanged in a single statement without recourse to a temporary variable. This idiom is characteristic of Python and should be preferred to the three-statement form used in other languages.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-7"></a>

## 07. 2.2.6.4 Augmented assignment

### Problem statement

Demonstrate augmented assignment using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support augmented assignment and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `250` in `stock_units`.
2. Update `stock_units` using `stock_units += 100`.
3. Display the results for inspection.
4. Update `stock_units` using `stock_units -= 60`.
5. Display the results for inspection.
6. Update `stock_units` using `stock_units //= 2`.
7. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [8]:
stock_units = 250
 
stock_units += 100          # goods received
print("After receipt :", stock_units)
 
stock_units -= 60           # goods issued
print("After issue   :", stock_units)
 
stock_units //= 2           # half transferred to a second store
print("After transfer:", stock_units)

After receipt : 350
After issue   : 290
After transfer: 145


### Explanation

An augmented assignment operator combines an arithmetic operation with an assignment. The statement stock_units += 100 is equivalent in effect to stock_units = stock_units + 100, but expresses the intention of updating an existing quantity more directly. Augmented forms exist for every arithmetic operator.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-8"></a>

## 08. 2.2.7 Dynamic typing and rebinding

### Problem statement

Demonstrate dynamic typing and rebinding using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support dynamic typing and rebinding and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `500` in `dose_mg`.
2. Display the results for inspection.
3. Store `2.5` in `dose_mg`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [9]:
dose_mg = 500
print("Value :", dose_mg)
print("Type  :", type(dose_mg))
 
dose_mg = 2.5               # the name now refers to a float object
print("Value :", dose_mg)
print("Type  :", type(dose_mg))

Value : 500
Type  : <class 'int'>
Value : 2.5
Type  : <class 'float'>


### Explanation

Caution: Dynamic typing is convenient, but reusing one name for two different meanings is a recognized source of error in calculation code. A name such as dose that holds a tablet count at one point and a mass in milligrams at another invites a silent unit error. Each name should serve one clearly documented purpose for the whole of its life.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-9"></a>

## 09. 2.2.8 Mutability and immutability

### Problem statement

Demonstrate mutability and immutability using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support mutability and immutability and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `'Aspirin'` in `label`.
2. Store `id(label)` in `original_id`.
3. Store `label + ' 75 mg'` in `label`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [10]:
label = "Aspirin"
original_id = id(label)
 
label = label + " 75 mg"
print(label)
print(original_id == id(label))      # is it still the same object?

Aspirin 75 mg
False


### Explanation

In the second example the list is mutable, and the append operation alters the existing object in place. The identity is unchanged.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-10"></a>

## 10. 2.2.8 Mutability and immutability

### Problem statement

Demonstrate mutability and immutability using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support mutability and immutability and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `[2.0, 3.5, 4.1]` in `temperature_log`.
2. Store `id(temperature_log)` in `original_id`.
3. Execute `temperature_log.append(5.2)`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [11]:
temperature_log = [2.0, 3.5, 4.1]
original_id = id(temperature_log)
 
temperature_log.append(5.2)
 
print(temperature_log)
print(original_id == id(temperature_log))

[2.0, 3.5, 4.1, 5.2]
True


### Explanation

The practical significance of mutability is the phenomenon of aliasing. When two names refer to the same mutable object, a modification made through one name is visible through the other. This behaviour is frequently unintended and can corrupt a record silently.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-11"></a>

## 11. 2.2.8 Mutability and immutability

### Problem statement

Demonstrate mutability and immutability using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support mutability and immutability and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `[2.0, 3.5, 4.1]` in `morning_log`.
2. Store `morning_log` in `evening_log`.
3. Execute `evening_log.append(8.9)`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [12]:
morning_log = [2.0, 3.5, 4.1]
evening_log = morning_log          # NOT a copy: a second name for one object
 
evening_log.append(8.9)
 
print("morning_log:", morning_log)
print("evening_log:", evening_log)

morning_log: [2.0, 3.5, 4.1, 8.9]
evening_log: [2.0, 3.5, 4.1, 8.9]


### Explanation

The appended reading has contaminated both records, because only one object exists. An independent copy must be requested explicitly by means of the copy() method.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-12"></a>

## 12. 2.2.8 Mutability and immutability

### Problem statement

Demonstrate mutability and immutability using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support mutability and immutability and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `[2.0, 3.5, 4.1]` in `morning_log`.
2. Store `morning_log.copy()` in `evening_log`.
3. Execute `evening_log.append(8.9)`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [13]:
morning_log = [2.0, 3.5, 4.1]
evening_log = morning_log.copy()   # an independent object
 
evening_log.append(8.9)
 
print("morning_log:", morning_log)
print("evening_log:", evening_log)

morning_log: [2.0, 3.5, 4.1]
evening_log: [2.0, 3.5, 4.1, 8.9]


### Explanation

Caution: In a program that maintains a stock register, a temperature log or a batch record — all of which are mutable structures — the statement backup = register does not create a backup. It creates a second route to the same data, and every subsequent alteration is applied to the supposed backup as well.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-13"></a>

## 13. 2.2.9 Object lifetime, reference counting and garbage collection

### Problem statement

Demonstrate object lifetime, reference counting and garbage collection using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support object lifetime, reference counting and garbage collection and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Import `sys`.
2. Store `[99.2, 98.7, 100.4]` in `assay_result`.
3. Display the results for inspection.
4. Store `assay_result` in `duplicate_reference`.
5. Display the results for inspection.
6. Remove the binding `duplicate_reference`.
7. Display the results for inspection.

### Important notes

Reference counts and object identities are implementation-dependent diagnostics. In CPython, id() commonly corresponds to a memory address, but Python only guarantees a unique identity during an object's lifetime.

### Code and executed output

The output appears directly below the code cell.

In [14]:
import sys
 
assay_result = [99.2, 98.7, 100.4]
print(sys.getrefcount(assay_result) - 1)
 
duplicate_reference = assay_result
print(sys.getrefcount(assay_result) - 1)
del duplicate_reference
print(sys.getrefcount(assay_result) - 1)

1
2
1


### Explanation

The count may be inspected with the getrefcount() function of the sys module. The value reported is one greater than the number of references held by the program, because the argument passed to the function constitutes a further temporary reference; the examples below subtract this.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-14"></a>

## 14. 2.2.10 Deleting a name

### Problem statement

Demonstrate deleting a name using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support deleting a name and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `'2027-06-30'` in `expiry_date`.
2. Display the results for inspection.
3. Remove the binding `expiry_date`.
4. Run the demonstration and catch the stated exception so the notebook can continue.

### Code and executed output

The output appears directly below the code cell.

In [15]:
expiry_date = "2027-06-30"
print(expiry_date)
del expiry_date
try:
    print(expiry_date)
except NameError as error:
    print(f"NameError: {error}")

2027-06-30
NameError: name 'expiry_date' is not defined


### Explanation

The del statement removes a name from the namespace. It deletes the name, not necessarily the object; the object survives if other names still refer to it. Any subsequent attempt to use the deleted name raises a NameError.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-15"></a>

## 15. 2.3.2 Integers (int)

### Problem statement

Demonstrate integers (int) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support integers (int) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `30` in `tablet_count`.
2. Store `1000000` in `batch_size`.
3. Store `-2` in `temperature_change`.
4. Store `0` in `zero_defects`.
5. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [16]:
tablet_count = 30
batch_size = 1_000_000              # underscores aid legibility only
temperature_change = -2
zero_defects = 0
 
print(tablet_count, batch_size, temperature_change, zero_defects)
print(2 ** 128)                     # arbitrary precision: no overflow
print(type(batch_size))

30 1000000 -2 0
340282366920938463463374607431768211456
<class 'int'>


### Explanation

Integer literals may also be written in binary, octal and hexadecimal notation using the prefixes 0b, 0o and 0x respectively. Such notation is encountered when interpreting barcode symbologies, instrument status registers and character encodings.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-16"></a>

## 16. 2.3.2 Integers (int)

### Problem statement

Demonstrate integers (int) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support integers (int) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [17]:
print(0b1010)                       # binary
print(0o17)                         # octal
print(0xFF)                         # hexadecimal
print(bin(10), oct(15), hex(255))   # the reverse conversions

10
15
255
0b1010 0o17 0xff


### Explanation

Integer literals may also be written in binary, octal and hexadecimal notation using the prefixes 0b, 0o and 0x respectively. Such notation is encountered when interpreting barcode symbologies, instrument status registers and character encodings.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-17"></a>

## 17. 2.3.3 Floating-point numbers (float)

### Problem statement

Demonstrate floating-point numbers (float) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support floating-point numbers (float) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `62.5` in `body_weight_kg`.
2. Store `0.0015` in `plasma_conc_g_ml`.
3. Store `7.4` in `ph_value`.
4. Store `85.6` in `dissolution_percent`.
5. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [18]:
body_weight_kg = 62.5
plasma_conc_g_ml = 1.5e-3           # 1.5 x 10^-3, that is 0.0015
ph_value = 7.4
dissolution_percent = 85.6
 
print(body_weight_kg, plasma_conc_g_ml, ph_value, dissolution_percent)

62.5 0.0015 7.4 85.6


### Explanation

A floating-point number represents a real number containing a fractional part. Floats are used for quantities that are measured rather than counted: body weight, plasma concentration, pH, dissolution percentage, volume and temperature. A float is created either by writing a decimal point or by using scientific notation, in which the letter e denotes multiplication by a power of ten.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-18"></a>

## 18. 2.3.3.1 The limits of floating-point precision

### Problem statement

Demonstrate the limits of floating-point precision using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support the limits of floating-point precision and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [19]:
print(0.1 + 0.2)
print(0.1 + 0.2 == 0.3)

0.30000000000000004
False


### Explanation

Three remedies are available. Rounding before comparison is adequate for display purposes. The math. isclose() function compares two values within a tolerance and is the appropriate general-purpose test. The Decimal type of the decimal module performs exact decimal arithmetic and is the correct choice for monetary values and for any calculation that must be reproducible to a stated number of decimal places.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-19"></a>

## 19. 2.3.3.1 The limits of floating-point precision

### Problem statement

Demonstrate the limits of floating-point precision using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support the limits of floating-point precision and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Import `math`.
2. Import `decimal`.
3. Display the results for inspection.
4. Store `Decimal('12.35')` in `unit_price`.
5. Store `3` in `quantity`.
6. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [20]:
import math
from decimal import Decimal
 
print(round(0.1 + 0.2, 2) == 0.3)
print(math.isclose(0.1 + 0.2, 0.3))
 
unit_price = Decimal("12.35")
quantity = 3
print(unit_price * quantity)
print(Decimal("0.1") + Decimal("0.2") == Decimal("0.3"))

True
True
37.05
True


### Explanation

Caution: Calculated floating-point quantities must never be compared with the == operator. A dose calculation that tests whether a computed value is exactly equal to a specification limit may fail even when the two agree to fifteen decimal places. Use math.isclose(), or compare against an interval, or perform the arithmetic with Decimal.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-20"></a>

## 20. 2.3.4 Complex numbers (complex)

### Problem statement

Demonstrate complex numbers (complex) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support complex numbers (complex) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `3 + 4j` in `impedance`.
2. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [21]:
impedance = 3 + 4j
 
print(impedance)
print(impedance.real, impedance.imag)
print(abs(impedance))               # the modulus
print(type(impedance))

(3+4j)
3.0 4.0
5.0
<class 'complex'>


### Explanation

A complex number consists of a real part and an imaginary part, the latter written with the suffix j. Complex numbers are not required in routine pharmacy calculations, but they arise in the analysis of alternating-current impedance in electroanalytical methods and in the signal processing that underlies spectroscopic instrumentation. They are described here for completeness of the type taxonomy.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-21"></a>

## 21. 2.3.5 Boolean values (bool)

### Problem statement

Demonstrate boolean values (bool) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support boolean values (bool) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `True` in `is_refrigerated`.
2. Store `False` in `is_expired`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [22]:
is_refrigerated = True
is_expired = False
print(is_refrigerated, is_expired)
print(type(is_refrigerated))

True False
<class 'bool'>


### Explanation

The Boolean type is a subclass of the integer type, and True and False behave as 1 and 0 respectively in arithmetic contexts. This is occasionally useful — a count of passing samples may be obtained by summing Boolean results — but it also explains why a Boolean may appear unexpectedly in a numerical calculation.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-22"></a>

## 22. 2.3.5 Boolean values (bool)

### Problem statement

Demonstrate boolean values (bool) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support boolean values (bool) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `True` in `is_refrigerated`.
2. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [23]:
is_refrigerated = True
print(isinstance(is_refrigerated, int))
print(True + True)
print(int(True), int(False))

True
2
1 0


### Explanation

Caution: The Boolean literals are True and False. The lower-case forms true and false raise a NameError, and the quoted forms "True" and "False" are strings, not Booleans. The latter distinction is a frequent source of error, because a non-empty string is always truthy: bool("False") evaluates to True.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-23"></a>

## 23. 2.3.6 Strings (str)

### Problem statement

Demonstrate strings (str) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support strings (str) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `'Amoxicillin'` in `drug_name`.
2. Store `'B2401A'` in `batch_number`.
3. Store `'Take one capsule three times daily.\nComplete the full course.'` in `counselling_note`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [24]:
drug_name = "Amoxicillin"
batch_number = 'B2401A'
counselling_note = """Take one capsule three times daily.
Complete the full course."""
 
print(drug_name)
print(batch_number)
print(counselling_note)

Amoxicillin
B2401A
Take one capsule three times daily.
Complete the full course.


### Explanation

Because a string is a sequence, its individual characters may be accessed by index. Indexing begins at zero; a negative index counts backwards from the end. A slice, written with a colon, extracts a range of characters from the start index up to but not including the stop index.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-24"></a>

## 24. 2.3.6 Strings (str)

### Problem statement

Demonstrate strings (str) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support strings (str) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `'Amoxicillin'` in `drug_name`.
2. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [25]:
drug_name = "Amoxicillin"
 
print(len(drug_name))               # number of characters
print(drug_name[0])                 # first character
print(drug_name[-1])                # last character
print(drug_name[0:4])               # characters 0, 1, 2 and 3
print(drug_name.upper())

11
A
n
Amox
AMOXICILLIN


### Explanation

Note.  A batch number such as "00125" must be stored as a string. Converting it to an integer yields 125 and destroys the leading zeros, after which the identifier no longer matches the physical label on the container.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-25"></a>

## 25. 2.3.7 Byte strings (bytes)

### Problem statement

Demonstrate byte strings (bytes) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support byte strings (bytes) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `b'8901234567890'` in `barcode`.
2. Display the results for inspection.
3. Store `'Paracetamol'` in `label_text`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [26]:
barcode = b"8901234567890"
print(barcode)
print(type(barcode), len(barcode))
print(barcode.decode("utf-8"))      # bytes to text
 
label_text = "Paracetamol"
print(label_text.encode("utf-8"))   # text to bytes

b'8901234567890'
<class 'bytes'> 13
8901234567890
b'Paracetamol'


### Explanation

A byte string is an immutable sequence of integers in the range 0 to 255, denoted by the prefix b before the opening quotation mark. Byte strings represent raw binary data rather than human-readable text, and are encountered when reading from laboratory instruments, when handling barcode data and when transmitting information over a network. Conversion between the str and bytes types is performed by the encode() and decode() methods.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-26"></a>

## 26. 2.3.8 Lists (list)

### Problem statement

Demonstrate lists (list) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support lists (list) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `[2.4, 3.1, 4.8, 2.9]` in `temperature_log_c`.
2. Execute `temperature_log_c.append(5.5)`.
3. Store `2.5` in `temperature_log_c[0]`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [27]:
temperature_log_c = [2.4, 3.1, 4.8, 2.9]
 
temperature_log_c.append(5.5)       # add a new reading
temperature_log_c[0] = 2.5          # correct the first reading
 
print(temperature_log_c)
print(len(temperature_log_c), min(temperature_log_c), max(temperature_log_c))
print(sum(temperature_log_c) / len(temperature_log_c))

[2.5, 3.1, 4.8, 2.9, 5.5]
5 2.5 5.5
3.7600000000000002


### Explanation

The mean value displayed illustrates the floating-point representation issue described in Section 2.3.3.1 and would normally be rounded for reporting.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-27"></a>

## 27. 2.3.9 Tuples (tuple)

### Problem statement

Demonstrate tuples (tuple) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support tuples (tuple) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `(250, 500)` in `dose_range_mg`.
2. Display the results for inspection.
3. Store `(500,)` in `single_strength`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [28]:
dose_range_mg = (250, 500)
 
print(dose_range_mg, type(dose_range_mg))
print(dose_range_mg[0], dose_range_mg[1])
 
single_strength = (500,)            # the trailing comma is essential
print(single_strength, type(single_strength))

(250, 500) <class 'tuple'>
250 500
(500,) <class 'tuple'>


### Explanation

A tuple is an immutable, ordered collection enclosed in parentheses. A tuple should be preferred to a list whenever the collection represents a fixed group of related values that must not be altered — a specification range, a pair of coordinates, a record that has been finalized. Immutability safeguards against accidental modification.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-28"></a>

## 28. 2.3.9 Tuples (tuple)

### Problem statement

Demonstrate tuples (tuple) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support tuples (tuple) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Run the demonstration and catch the stated exception so the notebook can continue.

### Code and executed output

The output appears directly below the code cell.

In [29]:
try:
    dose_range_mg = (250, 500)
    dose_range_mg[0] = 125
except TypeError as error:
    print(f"TypeError: {error}")

TypeError: 'tuple' object does not support item assignment


### Explanation

Caution: The trailing comma is what creates a single-element tuple, not the parentheses. The expression (500) is simply the integer 500 in brackets, whereas (500,) is a tuple of one element.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-29"></a>

## 29. 2.3.10 Sets and frozen sets (set, frozenset)

### Problem statement

Demonstrate sets and frozen sets (set, frozenset) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support sets and frozen sets (set, frozenset) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `{'tablet', 'capsule', 'syrup', 'tablet'}` in `dosage_forms`.
2. Display the results for inspection.
3. Execute `dosage_forms.add('injection')`.
4. Display the results for inspection.
5. Store `frozenset(['tablet', 'capsule'])` in `approved`.
6. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [30]:
dosage_forms = {"tablet", "capsule", "syrup", "tablet"}
 
print(len(dosage_forms))            # the duplicate has been discarded
print("capsule" in dosage_forms)    # membership test
 
dosage_forms.add("injection")
print(sorted(dosage_forms))         # sorted() gives a reproducible order
 
approved = frozenset(["tablet", "capsule"])
print(sorted(approved))
print(type(approved))

3
True
['capsule', 'injection', 'syrup', 'tablet']
['capsule', 'tablet']
<class 'frozenset'>


### Explanation

A set is a mutable, unordered collection of unique values enclosed in braces. Duplicate entries are discarded automatically, making the set the appropriate structure for compiling a list of distinct dosage forms, distinct suppliers, or distinct active ingredients. Because a set is unordered, you can't access its elements by index. A frozenset is the immutable counterpart.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-30"></a>

## 30. 2.3.11 Dictionaries (dict)

### Problem statement

Demonstrate dictionaries (dict) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support dictionaries (dict) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `{'Paracetamol': 250, 'Amoxicillin': 80, 'Metformin': 0}` in `stock_register`.
2. Display the results for inspection.
3. Store `120` in `stock_register['Metformin']`.
4. Store `45` in `stock_register['Ibuprofen']`.
5. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [31]:
stock_register = {"Paracetamol": 250, "Amoxicillin": 80, "Metformin": 0}
 
print(stock_register["Amoxicillin"])        # retrieve by key
 
stock_register["Metformin"] = 120           # update an existing entry
stock_register["Ibuprofen"] = 45            # insert a new entry
 
print(stock_register)
print(list(stock_register.keys()))
print(stock_register.get("Aspirin", 0))     # absent key, default returned

80
{'Paracetamol': 250, 'Amoxicillin': 80, 'Metformin': 120, 'Ibuprofen': 45}
['Paracetamol', 'Amoxicillin', 'Metformin', 'Ibuprofen']
0


### Explanation

Note: Retrieving an absent key with square brackets raises a KeyError and halts the program. The .get() method returns a stated default instead, and is the safer choice when a stock item may legitimately be missing from the register.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-31"></a>

## 31. 2.3.12 Null object (NoneType)

### Problem statement

Demonstrate null object (NoneType) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support null object (nonetype) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `None` in `assay_result`.
2. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [32]:
assay_result = None                 # the assay has not yet been performed
 
print(assay_result)
print(type(assay_result))
print(assay_result is None)         # identity test, not equality
print(bool(assay_result))           # None is falsy

None
<class 'NoneType'>
True
False


### Explanation

The object None is the sole instance of the type NoneType and denotes the deliberate absence of a value. It is used where a result has not yet been obtained, a measurement has not been recorded, or an optional item of information was not supplied. None must be distinguished carefully from the numeral zero and from the empty string: zero is a recorded measurement whose value happens to be nought, whereas None records that no measurement exists.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-32"></a>

## 32. 2.3.14 Determining the type: type() and isinstance()

### Problem statement

Demonstrate determining the type: type() and isinstance() using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support determining the type: type() and isinstance() and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `500` in `strength_mg`.
2. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [33]:
strength_mg = 500
 
print(type(strength_mg))
print(type(strength_mg) is int)
print(isinstance(strength_mg, int))
print(isinstance(strength_mg, (int, float)))     # either type accepted

<class 'int'>
True
True
True


### Explanation

The function isinstance() differs from type() in that it recognises inheritance. Because bool is a subclass of int, a Boolean value is an instance of int although its type is not int. Where a test must accept any numeric value, isinstance() with a tuple of acceptable types is the appropriate construction.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-33"></a>

## 33. 2.3.14 Determining the type: type() and isinstance()

### Problem statement

Demonstrate determining the type: type() and isinstance() using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support determining the type: type() and isinstance() and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `True` in `is_refrigerated`.
2. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [34]:
is_refrigerated = True
 
print(type(is_refrigerated) is int)          # exact type match
print(isinstance(is_refrigerated, int))      # inheritance recognised

False
True


### Explanation

The function isinstance() differs from type() in that it recognises inheritance. Because bool is a subclass of int, a Boolean value is an instance of int although its type is not int. Where a test must accept any numeric value, isinstance() with a tuple of acceptable types is the appropriate construction.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-34"></a>

## 34. 2.4.2 Implicit type conversion

### Problem statement

Demonstrate implicit type conversion using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support implicit type conversion and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `3` in `tablets`.
2. Store `2.5` in `strength_mg`.
3. Store `tablets * strength_mg` in `total_mg`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [35]:
tablets = 3                         # int
strength_mg = 2.5                   # float
total_mg = tablets * strength_mg    # int is promoted to float
 
print(total_mg, type(total_mg))
print(True + 10, type(True + 10))   # bool is promoted to int
print(5 / 2, type(5 / 2))           # true division always yields a float
print(4 / 2, type(4 / 2))           # even when the result is exact
print(2 + 3j, type(2 + 3j))         # int is promoted to complex

7.5 <class 'float'>
11 <class 'int'>
2.5 <class 'float'>
2.0 <class 'float'>
(2+3j) <class 'complex'>


### Explanation

No implicit conversion whatever takes place between text and numbers. The interpreter will not assume that a string of digits was intended as a number, because such an assumption could silently alter the meaning of an identifier. An attempt to combine the two raises a TypeError.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-35"></a>

## 35. 2.4.2 Implicit type conversion

### Problem statement

Demonstrate implicit type conversion using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support implicit type conversion and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Run the demonstration and catch the stated exception so the notebook can continue.

### Code and executed output

The output appears directly below the code cell.

In [36]:
try:
    print("500" + 5)
except TypeError as error:
    print(f"TypeError: {error}")

TypeError: can only concatenate str (not "int") to str


### Explanation

No implicit conversion whatever takes place between text and numbers. The interpreter will not assume that a string of digits was intended as a number, because such an assumption could silently alter the meaning of an identifier. An attempt to combine the two raises a TypeError.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-36"></a>

## 36. 2.4.3.1 Conversion to an integer: int()

### Problem statement

Demonstrate conversion to an integer: int() using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support conversion to an integer: int() and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [37]:
print(int("500"), type(int("500")))
print(int(7.9))                     # truncation, not rounding
print(int(-7.9))                    # truncation is towards zero
print(int(True))
print(int("1010", 2))               # binary string to integer
print(int("FF", 16))                # hexadecimal string to integer

500 <class 'int'>
7
-7
1
10
255


### Explanation

The function accepts a string of digits, a floating-point number or a Boolean. When applied to a float it truncates towards zero; it does not round. When a base is supplied as a second argument, the string is interpreted in that number system.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-37"></a>

## 37. 2.4.3.2 Conversion to a floating-point number: float()

### Problem statement

Demonstrate conversion to a floating-point number: float() using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support conversion to a floating-point number: float() and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [38]:
print(float("2.5"), type(float("2.5")))
print(float(500))
print(float("  3.75  "))            # surrounding spaces are ignored
print(float("1.5e-3"))              # scientific notation is accepted
print(float(True))

2.5 <class 'float'>
500.0
3.75
0.0015
1.0


### Explanation

The function accepts a string representing a decimal or scientific-notation number, an integer or a Boolean. Surrounding whitespace in a string is ignored, which is convenient when data have been entered with stray spaces.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-38"></a>

## 38. 2.4.3.3 Conversion to a string: str()

### Problem statement

Demonstrate conversion to a string: str() using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support conversion to a string: str() and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `2026` in `batch_year`.
2. Store `'B-' + str(batch_year)` in `batch_label`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [39]:
batch_year = 2026
batch_label = "B-" + str(batch_year)
 
print(batch_label, type(batch_label))
print(str(2.50))                    # the trailing zero is not preserved
print(str(True))
print(str(None))
print(str([2.4, 3.1]))

B-2026 <class 'str'>
2.5
True
None
[2.4, 3.1]


### Explanation

The function produces a readable textual representation of any object whatsoever, and never fails. It is required when a number must be joined to text by concatenation, as when a label is assembled from a prefix and a year.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-39"></a>

## 39. 2.4.3.4 Conversion to a Boolean: bool()

### Problem statement

Demonstrate conversion to a Boolean: bool() using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support conversion to a boolean: bool() and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [40]:
print(bool(0), bool(1), bool(-3))
print(bool(0.0), bool(0.1))
print(bool(""), bool("no"), bool("False"))
print(bool([]), bool([0]))
print(bool({}), bool(None))

False True True
False True
False True True
False True
False False


### Explanation

Caution: The expression bool("False") evaluates to True, and bool("no") likewise evaluates to True, because both strings are non-empty. The bool() function must therefore never be applied directly to a yes/no answer typed by a user. The correct construction normalizes the text and compares it explicitly: answer.strip().lower() == "yes".

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-40"></a>

## 40. 2.4.3.4 Conversion to a Boolean: bool()

### Problem statement

Demonstrate conversion to a Boolean: bool() using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support conversion to a boolean: bool() and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `'  Yes  '` in `answer`.
2. Store `answer.strip().lower() == 'yes'` in `is_sealed`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [41]:
answer = "  Yes  "
 
is_sealed = answer.strip().lower() == "yes"    # correct
print(is_sealed)
print(bool("no"))                              # incorrect: always True

True
True


### Explanation

Caution: The expression bool("False") evaluates to True, and bool("no") likewise evaluates to True, because both strings are non-empty. The bool() function must therefore never be applied directly to a yes/no answer typed by a user. The correct construction normalizes the text and compares it explicitly: answer.strip().lower() == "yes".

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-41"></a>

## 41. 2.4.3.5 Conversion between collection types

### Problem statement

Demonstrate conversion between collection types using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support conversion between collection types and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.
2. Store `[('Paracetamol', 250), ('Amoxicillin', 80)]` in `pairs`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [42]:
print(list("ABC"))                            # a string is a sequence
print(list((250, 500)))                       # tuple to list
print(tuple([2.4, 3.1]))                      # list to tuple
print(set([1, 2, 2, 3]))                      # duplicates discarded
 
pairs = [("Paracetamol", 250), ("Amoxicillin", 80)]
print(dict(pairs))                            # pairs to dictionary
 
print(complex(3, 4))

['A', 'B', 'C']
[250, 500]
(2.4, 3.1)
{1, 2, 3}
{'Paracetamol': 250, 'Amoxicillin': 80}
(3+4j)


### Explanation

Read the statements in order. The saved result shows the values produced by this cell; compare the value and its type or unit with the algorithm.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-42"></a>

## 42. 2.4.3.6 Conversion between numeric representations

### Problem statement

Demonstrate conversion between numeric representations using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support conversion between numeric representations and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [43]:
print(bin(10), oct(15), hex(255))
print(ord("A"), chr(66))
print(int(bin(10), 2))              # and back again

0b1010 0o17 0xff
65 B
10


### Explanation

The functions bin(), oct() and hex() convert an integer to a string in the corresponding base, and ord() and chr() convert between a character and its Unicode code point.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-43"></a>

## 43. 2.4.4 Loss of precision in conversion

### Problem statement

Demonstrate loss of precision in conversion using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support loss of precision in conversion and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `502.7` in `tablet_weight_mg`.
2. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [44]:
tablet_weight_mg = 502.7
 
print(int(tablet_weight_mg))        # truncation
print(round(tablet_weight_mg))      # rounding
print(int(-502.7), round(-502.7))

502
503
-502 -503


### Explanation

The round() function itself implements round-half-to-even, sometimes termed banker’s rounding, in which a value exactly midway between two integers is rounded to the nearer even integer. This convention avoids the systematic upward bias that arises when a large number of half-values are always rounded away from zero, but it surprises those who expect the arithmetic rule taught in school.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-44"></a>

## 44. 2.4.4 Loss of precision in conversion

### Problem statement

Demonstrate loss of precision in conversion using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support loss of precision in conversion and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [45]:
print(round(2.5), round(3.5), round(0.5))

2 4 0


### Explanation

A further subtlety arises when round() is applied to a decimal fraction that has no exact binary representation. The stored value may lie fractionally below the apparent midpoint, in which case the result is rounded downwards.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-45"></a>

## 45. 2.4.4 Loss of precision in conversion

### Problem statement

Demonstrate loss of precision in conversion using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support loss of precision in conversion and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [46]:
print(round(502.675, 2))            # this value rounds to 502.68
print(round(2.675, 2))

502.68
2.67


### Explanation

Caution: Truncation is not rounding. A calculated dose of 502.7 mg converted with int() becomes 502 mg, an understatement of the computed value. Where a dose or a count must be rounded, use round() and state in a comment which rounding convention the calculation requires. For monetary values and for any calculation subject to audit, use the Decimal type with an explicitly stated rounding mode.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-46"></a>

## 46. 2.4.5 Errors arising from invalid conversion

### Problem statement

Demonstrate errors arising from invalid conversion using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support errors arising from invalid conversion and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Run the demonstration and catch the stated exception so the notebook can continue.

### Code and executed output

The output appears directly below the code cell.

In [47]:
try:
    print(int("12.5"))
except ValueError as error:
    print(f"ValueError: {error}")

ValueError: invalid literal for int() with base 10: '12.5'


### Explanation

The remedy is a two-stage conversion through float, followed by truncation or rounding as the application requires.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-47"></a>

## 47. 2.4.5 Errors arising from invalid conversion

### Problem statement

Demonstrate errors arising from invalid conversion using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support errors arising from invalid conversion and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `'12.5'` in `entered_value`.
2. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [48]:
entered_value = "12.5"
 
print(int(float(entered_value)))    # truncate
print(round(float(entered_value)))  # round

12
12


### Explanation

The remedy is a two-stage conversion through float, followed by truncation or rounding as the application requires.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-48"></a>

## 48. 2.4.5 Errors arising from invalid conversion

### Problem statement

Demonstrate errors arising from invalid conversion using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support errors arising from invalid conversion and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Run the demonstration and catch the stated exception so the notebook can continue.

### Code and executed output

The output appears directly below the code cell.

In [49]:
try:
    print(float("five hundred"))
except ValueError as error:
    print(f"ValueError: {error}")

ValueError: could not convert string to float: 'five hundred'


### Explanation

A TypeError arises where the argument is of a type that cannot be converted at all, such as the null object.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-49"></a>

## 49. 2.4.5 Errors arising from invalid conversion

### Problem statement

Demonstrate errors arising from invalid conversion using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support errors arising from invalid conversion and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Run the demonstration and catch the stated exception so the notebook can continue.

### Code and executed output

The output appears directly below the code cell.

In [50]:
try:
    print(int(None))
except TypeError as error:
    print(f"TypeError: {error}")

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'


### Explanation

A TypeError arises where the argument is of a type that cannot be converted at all, such as the null object.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-50"></a>

## 50. 2.5.1 The input() function

### Problem statement

Demonstrate the input() function using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support the input() function and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `iter(['Amoxicillin'])` in `_sample_answers`.
2. Store `classroom_input('Enter drug name: ')` in `drug_name`.
3. Display the results for inspection.

### Important notes

Saved output uses these sample entries in order: `Amoxicillin`. Set INTERACTIVE_INPUT = True in the setup cell to type your own entries.

### Code and executed output

The output appears directly below the code cell.

In [51]:
_sample_answers = iter(['Amoxicillin'])

drug_name = classroom_input("Enter drug name: ")
 
print("Recorded:", drug_name)
print(type(drug_name))

Enter drug name: Amoxicillin
Recorded: Amoxicillin
<class 'str'>


### Explanation

Caution: The input() function returns a string in every case, without exception. Even when the user types 500, the value returned is the three-character text "500" and not the number 500. Applying an arithmetic operator to it produces either a wrong answer or an exception, as the following example demonstrates.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-51"></a>

## 51. 2.5.1 The input() function

### Problem statement

Demonstrate the input() function using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support the input() function and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `iter(['500'])` in `_sample_answers`.
2. Store `classroom_input('Enter strength in mg: ')` in `strength`.
3. Display the results for inspection.

### Important notes

Saved output uses these sample entries in order: `500`. Set INTERACTIVE_INPUT = True in the setup cell to type your own entries.

### Code and executed output

The output appears directly below the code cell.

In [52]:
_sample_answers = iter(['500'])

strength = classroom_input("Enter strength in mg: ")
 
print(strength, type(strength))
print(strength + strength)          # concatenation, not addition

Enter strength in mg: 500
500 <class 'str'>
500500


### Explanation

Caution: The input() function returns a string in every case, without exception. Even when the user types 500, the value returned is the three-character text "500" and not the number 500. Applying an arithmetic operator to it produces either a wrong answer or an exception, as the following example demonstrates.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-52"></a>

## 52. 2.5.1.1 Reading numeric values

### Problem statement

Demonstrate reading numeric values using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support reading numeric values and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `iter(['500', '2'])` in `_sample_answers`.
2. Store `int(classroom_input('Enter strength in mg: '))` in `strength_mg`.
3. Store `int(classroom_input('Enter number of tablets: '))` in `tablets`.
4. Display the results for inspection.

### Important notes

Saved output uses these sample entries in order: `500`, `2`. Set INTERACTIVE_INPUT = True in the setup cell to type your own entries.

### Code and executed output

The output appears directly below the code cell.

In [53]:
_sample_answers = iter(['500', '2'])

strength_mg = int(classroom_input("Enter strength in mg: "))
tablets = int(classroom_input("Enter number of tablets: "))
print("Total dose:", strength_mg * tablets, "mg")

Enter strength in mg: 500
Enter number of tablets: 2
Total dose: 1000 mg


### Explanation

The choice between int() and float() follows the distinction between counted and measured quantities established in Section 2.3. A count of tablets is read with int(); a body weight, a volume or an assay result is read with float().

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-53"></a>

## 53. 2.5.1.2 Reading several values from one line

### Problem statement

Demonstrate reading several values from one line using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support reading several values from one line and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `iter(['2.4 3.1 4.8'])` in `_sample_answers`.
2. Store `classroom_input('Enter three temperatures separated by spaces: ')` in `readings`.
3. Store `readings.split()` in `values`.
4. Display the results for inspection.
5. Store `[float(v) for v in values]` in `numbers`.
6. Display the results for inspection.

### Important notes

Saved output uses these sample entries in order: `2.4 3.1 4.8`. Set INTERACTIVE_INPUT = True in the setup cell to type your own entries.

### Code and executed output

The output appears directly below the code cell.

In [54]:
_sample_answers = iter(['2.4 3.1 4.8'])

readings = classroom_input("Enter three temperatures separated by spaces: ")
values = readings.split()
print(values)
numbers = [float(v) for v in values]
print(numbers)
print("Mean:", sum(numbers) / len(numbers))

Enter three temperatures separated by spaces: 2.4 3.1 4.8
['2.4', '3.1', '4.8']
[2.4, 3.1, 4.8]
Mean: 3.4333333333333336


### Explanation

Note: The construction [float(v) for v in values] is a list comprehension. It is introduced formally in a later chapter; at this stage it may be read simply as an instruction to convert every element of the list to a float.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-54"></a>

## 54. 2.5.2.1 Displaying objects

### Problem statement

Demonstrate displaying objects using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support displaying objects and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [55]:
print("Batch inspection report")
print()                             # blank line
print("Drug:", "Amoxicillin", "Batch:", "B2401A")
print(500)
print(2.5, True, None)

Batch inspection report

Drug: Amoxicillin Batch: B2401A
500
2.5 True None


### Explanation

Any number of objects of any type may be supplied. Each is converted to text by str() and the results are written in order, separated by the value of sep. A call with no arguments prints an empty line, which is useful for spacing a report.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-55"></a>

## 55. 2.5.2.2 The sep argument

### Problem statement

Demonstrate the sep argument using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support the sep argument and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [56]:
print("Amoxicillin", "B2401A", "2027-06-30", sep=" | ")
print("2027", "06", "30", sep="-")
print("Paracetamol", 250, sep="")

Amoxicillin | B2401A | 2027-06-30
2027-06-30
Paracetamol250


### Explanation

The sep argument determines the string inserted between consecutive objects. Its default is a single space. Setting it to the empty string joins the objects without any separator, which is useful when constructing a code or an identifier.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-56"></a>

## 56. 2.5.2.3 The end argument

### Problem statement

Demonstrate the end argument using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support the end argument and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [57]:
print("Temperature: ", end="")
print("2.4 C")
 
print("Reading 1", end=" -> ")
print("Reading 2")
 
print("A", end="")
print("B", end="")
print("C")

Temperature: 2.4 C
Reading 1 -> Reading 2
ABC


### Explanation

The end argument determines the string appended after the final object. Its default is the newline character, which is why consecutive calls to print() ordinarily produce consecutive lines. Setting end to the empty string or to a space causes the next call to continue on the same line.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-57"></a>

## 57. 2.5.2.3 The end argument

### Problem statement

Demonstrate the end argument using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support the end argument and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [58]:
print("2.4", "3.1", "4.8", sep=" C, ", end=" C\n")
print("Done")

2.4 C, 3.1 C, 4.8 C
Done


### Explanation

The end argument determines the string appended after the final object. Its default is the newline character, which is why consecutive calls to print() ordinarily produce consecutive lines. Setting end to the empty string or to a space causes the next call to continue on the same line.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-58"></a>

## 58. 2.5.2.4 The file argument

### Problem statement

Demonstrate the file argument using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support the file argument and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Import `sys`.
2. Display the results for inspection.
3. Open the specified file with a context manager and complete the indented file operation.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [59]:
import sys
 
print("Cold-chain excursion detected", file=sys.stderr)
print("Normal report line", file=sys.stdout)
with open(OUTPUT_DIR / "temperature_log.txt", "w", encoding="utf-8") as handle:
    print("2.4", "3.1", "4.8", sep=",", file=handle)
 
with open(OUTPUT_DIR / "temperature_log.txt", encoding="utf-8") as handle:
    print(handle.read(), end="")

Normal report line
2.4,3.1,4.8


Cold-chain excursion detected


### Explanation

The message written to the standard error stream appears separately and is not part of the ordinary output shown above.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-59"></a>

## 59. 2.5.2.5 The flush argument

### Problem statement

Demonstrate the flush argument using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support the flush argument and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [60]:
print("Processing batch", end="", flush=True)
# a lengthy calculation would occur here
print(" ... complete")

Processing batch ... complete


### Explanation

Output is ordinarily held in a buffer and written out when the buffer is full or when a newline is encountered. Setting flush to True forces the buffer to be written immediately. This is required when a progress message must appear before a long computation begins, since without it the message may remain invisible until the computation has finished.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-60"></a>

## 60. 2.5.3 Escape sequences

### Problem statement

Demonstrate escape sequences using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support escape sequences and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [61]:
print("Drug:\tAmoxicillin")
print("Line one\nLine two")
print("Batch \"B2401A\" verified")
print("Path: C:\\pharmacy\\records")
print("Storage: 2 to 8 \u00b0C")
print(r"Raw string: C:\pharmacy\records")

Drug:	Amoxicillin
Line one
Line two
Batch "B2401A" verified
Path: C:\pharmacy\records
Storage: 2 to 8 °C
Raw string: C:\pharmacy\records


### Explanation

An escape sequence is a combination of the backslash character with one or more further characters, which together denote a single character that cannot conveniently be typed directly. Escape sequences are interpreted within string literals.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-61"></a>

## 61. 2.5.4.1 Percentage formatting

### Problem statement

Demonstrate percentage formatting using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support percentage formatting and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `'Amoxicillin'` in `drug`.
2. Store `500` in `strength`.
3. Store `2.4567` in `conc`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [62]:
drug = "Amoxicillin"
strength = 500
conc = 2.4567
 
print("Drug: %s, Strength: %d mg" % (drug, strength))
print("Concentration: %.2f mg/mL" % conc)
print("Stock: %5d units" % 42)
print("Yield: %6.2f%%" % 92.456)

Drug: Amoxicillin, Strength: 500 mg
Concentration: 2.46 mg/mL
Stock:    42 units
Yield:  92.46%


### Explanation

The principal specifications are %s for a string, %d for an integer, and %f for a floating-point number, the last accepting a precision written as %.<n>f. A literal percentage sign is written %%.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-62"></a>

## 62. 2.5.4.2 The str.format() method

### Problem statement

Demonstrate the str.format() method using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support the str.format() method and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `'Amoxicillin'` in `drug`.
2. Store `500` in `strength`.
3. Store `2.4567` in `conc`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [63]:
drug = "Amoxicillin"
strength = 500
conc = 2.4567
 
print("Drug: {}, Strength: {} mg".format(drug, strength))
print("Drug: {0}, Batch: {1}, Drug again: {0}".format(drug, "B2401A"))
print("Drug: {name}, Strength: {mg} mg".format(name=drug, mg=strength))
print("Concentration: {:.2f} mg/mL".format(conc))
print("|{:<15}|{:>8}|{:^10}|".format("Paracetamol", 250, "OK"))

Drug: Amoxicillin, Strength: 500 mg
Drug: Amoxicillin, Batch: B2401A, Drug again: Amoxicillin
Drug: Amoxicillin, Strength: 500 mg
Concentration: 2.46 mg/mL
|Paracetamol    |     250|    OK    |


### Explanation

The format() method of the string type replaces braces in the template with the arguments supplied. The braces may be empty, in which case the arguments are consumed in order; they may contain a positional index, which permits an argument to be used more than once; or they may contain a keyword.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-63"></a>

## 63. 2.5.4.3 Formatted string literals (f-strings)

### Problem statement

Demonstrate formatted string literals (f-strings) using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support formatted string literals (f-strings) and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `'Amoxicillin'` in `drug`.
2. Store `500` in `strength_mg`.
3. Store `3` in `tablets`.
4. Store `2.4567` in `conc`.
5. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [64]:
drug = "Amoxicillin"
strength_mg = 500
tablets = 3
conc = 2.4567
 
print(f"Drug: {drug}")
print(f"Total dose: {strength_mg * tablets} mg")      # an expression
print(f"Concentration: {conc:.2f} mg/mL")
print(f"Uppercase: {drug.upper()}")                   # a method call

Drug: Amoxicillin
Total dose: 1500 mg
Concentration: 2.46 mg/mL
Uppercase: AMOXICILLIN


### Explanation

A formatted string literal, universally termed an f-string, is a string prefixed with the letter f in which any expression enclosed in braces is evaluated and its result inserted at that point. The f-string is the recommended mechanism for new code because the expression appears where its value will be displayed, and the reader need not match a template against a separate list of arguments.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-64"></a>

## 64. 2.5.4.4 The format specification

### Problem statement

Demonstrate the format specification using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support the format specification and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `500` in `strength_mg`.
2. Store `2.4567` in `conc`.
3. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [65]:
strength_mg = 500
conc = 2.4567
 
print(f"{'Drug':<15}{'Strength':>10}{'Stock':>8}")
print(f"{'Paracetamol':<15}{'500 mg':>10}{250:>8}")
print(f"{'Amoxicillin':<15}{'250 mg':>10}{80:>8}")
print(f"{'Total':<15}{'':>10}{330:>8}")
print(f"{42:05d}")
print(f"{123456.789:,.2f}")
print(f"{0.9245:.1%}")
print(f"{1500000:.2e}")
print(f"{strength_mg=}")
print(f"{conc=:.3f}")

Drug             Strength   Stock
Paracetamol        500 mg     250
Amoxicillin        250 mg      80
Total                         330
00042
123,456.79
92.5%
1.50e+06
strength_mg=500
conc=2.457


### Explanation

Whatever follows the colon inside the braces constitutes the format specification, which controls alignment, width, grouping, precision and presentation. Its components are set out in Figure 2.11 and enumerated in Table 2.11:

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

<a id="example-2-65"></a>

## 65. 2.5.5 Rounding for display compared with rounding of values

### Problem statement

Demonstrate rounding for display compared with rounding of values using the simulated values or objects in the cell below.

### Objective

Understand how the Python operations in this example support rounding for display compared with rounding of values and interpret the result correctly.

### Pharmacy context

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

### Algorithm

1. Store `2.4567` in `value`.
2. Store `round(value, 2)` in `rounded`.
3. Store `f'{value:.2f}'` in `displayed`.
4. Display the results for inspection.

### Code and executed output

The output appears directly below the code cell.

In [66]:
value = 2.4567
 
rounded = round(value, 2)
displayed = f"{value:.2f}"
 
print(rounded, type(rounded))
print(displayed, type(displayed))

2.46 <class 'float'>
2.46 <class 'str'>


### Explanation

Caution: A dose calculation should be carried out at full precision and rounded once, at the point of display or at the point of dispensing. Rounding at each intermediate step accumulates error. Note also that the result of a format specification is a string and cannot be used in further arithmetic.

### Interpretation

The meaning and unit determine how a pharmacy value should be stored. A missing assay is not zero, a batch identifier is text, and a displayed dose is only classroom arithmetic.

## Review and practice

- Change one simulated input and predict the effect before rerunning the relevant cell.
- State the unit and meaning of each reported result.
- Explain one input condition or limitation that matters for the example.
- Restart the kernel and run all cells to check that the notebook is reproducible.

## Source and validation

Adapted from **2992_02_Final_KS_Revised.docx**. Worked programs and the complete code demonstrations are retained in chapter order. Installation commands are optional instructions; intentionally broken debugging examples are shown as corrected solutions. Notebook-specific changes are recorded in `Notebook_Guide_and_Validation.md`.